// PRODUCTOS BIMBO COMPLETOS (45 productos)

import { Product } from "./data";

export const bimboProducts: Product[] = [
  // Pan de caja (12 productos)
  {
    id: "pan-blanco-bimbo-grande",
    name: "Pan Blanco Bimbo Grande",
    price: 38,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Pan de caja Bimbo blanco grande, suave y fresco",
    inStock: true,
    stock: 25,
    brand: "Bimbo",
    tags: ["pan", "blanco", "grande", "suave"],
    rating: 4.6,
    reviewCount: 189,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-integral-bimbo",
    name: "Pan Integral Bimbo",
    price: 42,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Pan integral Bimbo rico en fibra y nutrientes",
    inStock: true,
    stock: 20,
    brand: "Bimbo",
    tags: ["pan", "integral", "fibra", "saludable"],
    rating: 4.5,
    reviewCount: 156,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-avena-miel-bimbo",
    name: "Pan Avena y Miel Bimbo",
    price: 45,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Pan de avena con miel, dulce y nutritivo",
    inStock: true,
    stock: 18,
    brand: "Bimbo",
    tags: ["avena", "miel", "dulce", "nutritivo"],
    rating: 4.7,
    reviewCount: 134,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-artesano-bimbo",
    name: "Pan Artesano Bimbo",
    price: 48,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Pan estilo artesano con corteza crujiente",
    inStock: true,
    stock: 15,
    brand: "Bimbo",
    tags: ["artesano", "corteza", "crujiente", "premium"],
    rating: 4.8,
    reviewCount: 98,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-multigrano-bimbo",
    name: "Pan Multigrano Bimbo",
    price: 46,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Pan con mezcla de granos y semillas",
    inStock: true,
    stock: 16,
    brand: "Bimbo",
    tags: ["multigrano", "semillas", "granos", "nutritivo"],
    rating: 4.6,
    reviewCount: 87,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-sin-corteza-bimbo",
    name: "Pan Sin Corteza Bimbo",
    price: 40,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image:
      "https://images.pexels.com/photos/20168404/pexels-photo-20168404.jpeg",
    description: "Pan blanco sin corteza, perfecto para niños",
    inStock: true,
    stock: 22,
    brand: "Bimbo",
    tags: ["sin corteza", "niños", "suave", "blanco"],
    rating: 4.4,
    reviewCount: 123,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-doble-fibra-bimbo",
    name: "Pan Doble Fibra Bimbo",
    price: 44,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Pan con doble contenido de fibra",
    inStock: true,
    stock: 17,
    brand: "Bimbo",
    tags: ["doble fibra", "digestión", "saludable", "bienestar"],
    rating: 4.5,
    reviewCount: 76,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-linaza-bimbo",
    name: "Pan con Linaza Bimbo",
    price: 47,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Pan enriquecido con semillas de linaza",
    inStock: true,
    stock: 14,
    brand: "Bimbo",
    tags: ["linaza", "semillas", "omega", "saludable"],
    rating: 4.6,
    reviewCount: 92,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-centeno-bimbo",
    name: "Pan de Centeno Bimbo",
    price: 45,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Pan de centeno tradicional europeo",
    inStock: true,
    stock: 12,
    brand: "Bimbo",
    tags: ["centeno", "tradicional", "europeo", "distintivo"],
    rating: 4.3,
    reviewCount: 58,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-hot-dog-bimbo",
    name: "Pan para Hot Dog Bimbo",
    price: 35,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image:
      "https://images.pexels.com/photos/20168404/pexels-photo-20168404.jpeg",
    description: "Pan especial para hot dogs y salchichas",
    inStock: true,
    stock: 28,
    brand: "Bimbo",
    tags: ["hot dog", "salchicha", "especial", "parrilla"],
    rating: 4.4,
    reviewCount: 167,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-hamburguesa-bimbo",
    name: "Pan para Hamburguesa Bimbo",
    price: 38,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image:
      "https://images.pexels.com/photos/20168404/pexels-photo-20168404.jpeg",
    description: "Pan suave para hamburguesas con ajonjolí",
    inStock: true,
    stock: 24,
    brand: "Bimbo",
    tags: ["hamburguesa", "ajonjolí", "suave", "parrilla"],
    rating: 4.5,
    reviewCount: 134,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-tostado-blanco-bimbo",
    name: "Pan Tostado Blanco Bimbo",
    price: 32,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image:
      "https://images.pexels.com/photos/20168404/pexels-photo-20168404.jpeg",
    description: "Pan de molde blanco para tostar",
    inStock: true,
    stock: 30,
    brand: "Bimbo",
    tags: ["tostado", "molde", "blanco", "desayuno"],
    rating: 4.3,
    reviewCount: 98,
    deliveryTime: "15-20 min",
  },

  // Pan tostado e integral (8 productos)
  {
    id: "tostadas-horneadas-bimbo",
    name: "Tostadas Horneadas Bimbo",
    price: 28,
    category: "panaderia-bimbo",
    subcategory: "pan-tostado",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Tostadas horneadas crujientes para antojitos",
    inStock: true,
    stock: 35,
    brand: "Bimbo",
    tags: ["tostadas", "horneadas", "crujientes", "antojitos"],
    rating: 4.4,
    reviewCount: 156,
    deliveryTime: "15-20 min",
  },
  {
    id: "tostadas-integrales-bimbo",
    name: "Tostadas Integrales Bimbo",
    price: 32,
    category: "panaderia-bimbo",
    subcategory: "pan-tostado",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Tostadas integrales ricas en fibra",
    inStock: true,
    stock: 28,
    brand: "Bimbo",
    tags: ["tostadas", "integrales", "fibra", "saludable"],
    rating: 4.5,
    reviewCount: 87,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-tostado-integral-bimbo",
    name: "Pan Tostado Integral Bimbo",
    price: 36,
    category: "panaderia-bimbo",
    subcategory: "pan-tostado",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Pan tostado integral para desayuno saludable",
    inStock: true,
    stock: 22,
    brand: "Bimbo",
    tags: ["tostado", "integral", "desayuno", "saludable"],
    rating: 4.6,
    reviewCount: 92,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-tostado-multigrano-bimbo",
    name: "Pan Tostado Multigrano Bimbo",
    price: 38,
    category: "panaderia-bimbo",
    subcategory: "pan-tostado",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Pan tostado con mezcla de granos",
    inStock: true,
    stock: 18,
    brand: "Bimbo",
    tags: ["tostado", "multigrano", "granos", "nutritivo"],
    rating: 4.7,
    reviewCount: 73,
    deliveryTime: "15-20 min",
  },
  {
    id: "bagels-bimbo",
    name: "Bagels Bimbo",
    price: 42,
    category: "panaderia-bimbo",
    subcategory: "pan-tostado",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Bagels estilo americano para tostar",
    inStock: true,
    stock: 16,
    brand: "Bimbo",
    tags: ["bagels", "americano", "tostar", "versátil"],
    rating: 4.5,
    reviewCount: 64,
    deliveryTime: "15-20 min",
  },
  {
    id: "english-muffins-bimbo",
    name: "English Muffins Bimbo",
    price: 40,
    category: "panaderia-bimbo",
    subcategory: "pan-tostado",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Panecillos ingleses para tostar",
    inStock: true,
    stock: 14,
    brand: "Bimbo",
    tags: ["english muffin", "inglés", "tostar", "clásico"],
    rating: 4.4,
    reviewCount: 56,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-pita-bimbo",
    name: "Pan Pita Bimbo",
    price: 35,
    category: "panaderia-bimbo",
    subcategory: "pan-tostado",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Pan pita árabe para rellenar",
    inStock: true,
    stock: 20,
    brand: "Bimbo",
    tags: ["pita", "árabe", "rellenar", "mediterráneo"],
    rating: 4.3,
    reviewCount: 78,
    deliveryTime: "15-20 min",
  },
  {
    id: "croutons-bimbo",
    name: "Croutons Bimbo",
    price: 25,
    category: "panaderia-bimbo",
    subcategory: "pan-tostado",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/1382904/pexels-photo-1382904.jpeg",
    description: "Cubitos de pan tostado para ensaladas",
    inStock: true,
    stock: 32,
    brand: "Bimbo",
    tags: ["croutons", "ensaladas", "cubitos", "crujientes"],
    rating: 4.2,
    reviewCount: 89,
    deliveryTime: "15-20 min",
  },

  // Pasteles y roles (10 productos)
  {
    id: "gansito-bimbo",
    name: "Gansito Bimbo",
    price: 12,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/5507697/pexels-photo-5507697.jpeg",
    description: "Pastelito Gansito con crema y mermelada",
    inStock: true,
    stock: 48,
    brand: "Bimbo",
    tags: ["gansito", "crema", "mermelada", "clásico"],
    rating: 4.8,
    reviewCount: 267,
    deliveryTime: "15-20 min",
  },
  {
    id: "submarino-bimbo",
    name: "Submarino Bimbo",
    price: 12,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/5507697/pexels-photo-5507697.jpeg",
    description: "Pastelito Submarino relleno de crema",
    inStock: true,
    stock: 42,
    brand: "Bimbo",
    tags: ["submarino", "crema", "relleno", "favorito"],
    rating: 4.7,
    reviewCount: 189,
    deliveryTime: "15-20 min",
  },
  {
    id: "negrito-bimbo",
    name: "Negrito Bimbo",
    price: 12,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/5507697/pexels-photo-5507697.jpeg",
    description: "Pastelito Negrito de chocolate",
    inStock: true,
    stock: 40,
    brand: "Bimbo",
    tags: ["negrito", "chocolate", "oscuro", "tradicional"],
    rating: 4.6,
    reviewCount: 156,
    deliveryTime: "15-20 min",
  },
  {
    id: "pinguinos-bimbo",
    name: "Pingüinos Bimbo",
    price: 15,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/5507697/pexels-photo-5507697.jpeg",
    description: "Pastelitos Pingüinos con crema y coco",
    inStock: true,
    stock: 35,
    brand: "Bimbo",
    tags: ["pingüinos", "crema", "coco", "premium"],
    rating: 4.9,
    reviewCount: 298,
    deliveryTime: "15-20 min",
  },
  {
    id: "roles-canela-bimbo",
    name: "Roles de Canela Bimbo",
    price: 18,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/5507697/pexels-photo-5507697.jpeg",
    description: "Roles de canela esponjosos y dulces",
    inStock: true,
    stock: 28,
    brand: "Bimbo",
    tags: ["roles", "canela", "esponjosos", "dulces"],
    rating: 4.5,
    reviewCount: 134,
    deliveryTime: "15-20 min",
  },
  {
    id: "mantecadas-bimbo",
    name: "Mantecadas Bimbo",
    price: 22,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/5507697/pexels-photo-5507697.jpeg",
    description: "Mantecadas tradicionales suaves",
    inStock: true,
    stock: 24,
    brand: "Bimbo",
    tags: ["mantecadas", "tradicionales", "suaves", "caseras"],
    rating: 4.4,
    reviewCount: 87,
    deliveryTime: "15-20 min",
  },
  {
    id: "donitas-bimbo",
    name: "Donitas Bimbo",
    price: 16,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/5507697/pexels-photo-5507697.jpeg",
    description: "Mini donas glaseadas Bimbo",
    inStock: true,
    stock: 36,
    brand: "Bimbo",
    tags: ["donitas", "glaseadas", "mini", "dulces"],
    rating: 4.6,
    reviewCount: 167,
    deliveryTime: "15-20 min",
  },
  {
    id: "choco-roles-bimbo",
    name: "Choco Roles Bimbo",
    price: 20,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/5507697/pexels-photo-5507697.jpeg",
    description: "Roles rellenos de chocolate",
    inStock: true,
    stock: 30,
    brand: "Bimbo",
    tags: ["choco roles", "chocolate", "rellenos", "intenso"],
    rating: 4.7,
    reviewCount: 123,
    deliveryTime: "15-20 min",
  },
  {
    id: "panque-bimbo",
    name: "Panqué Bimbo",
    price: 25,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/5507697/pexels-photo-5507697.jpeg",
    description: "Panqué esponjoso individual",
    inStock: true,
    stock: 26,
    brand: "Bimbo",
    tags: ["panqué", "esponjoso", "individual", "clásico"],
    rating: 4.3,
    reviewCount: 94,
    deliveryTime: "15-20 min",
  },
  {
    id: "bubulubu-bimbo",
    name: "Bubulubu Bimbo",
    price: 14,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/5507697/pexels-photo-5507697.jpeg",
    description: "Pastelito Bubulubu con malvavisco",
    inStock: true,
    stock: 38,
    brand: "Bimbo",
    tags: ["bubulubu", "malvavisco", "suave", "nostálgico"],
    rating: 4.5,
    reviewCount: 176,
    deliveryTime: "15-20 min",
  },

  // Galletas y cookies (8 productos)
  {
    id: "galletas-mamut-bimbo",
    name: "Galletas Mamut Bimbo",
    price: 18,
    category: "panaderia-bimbo",
    subcategory: "galletas-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/64613/pexels-photo-64613.jpeg",
    description: "Galletas Mamut con chips de chocolate",
    inStock: true,
    stock: 32,
    brand: "Bimbo",
    tags: ["mamut", "chocolate", "chips", "crujientes"],
    rating: 4.7,
    reviewCount: 189,
    deliveryTime: "15-20 min",
  },
  {
    id: "cookies-chips-bimbo",
    name: "Cookies con Chips Bimbo",
    price: 22,
    category: "panaderia-bimbo",
    subcategory: "galletas-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/64613/pexels-photo-64613.jpeg",
    description: "Cookies americanas con chips de chocolate",
    inStock: true,
    stock: 28,
    brand: "Bimbo",
    tags: ["cookies", "americanas", "chips", "chocolate"],
    rating: 4.6,
    reviewCount: 134,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-marias-bimbo",
    name: "Galletas Marías Bimbo",
    price: 16,
    category: "panaderia-bimbo",
    subcategory: "galletas-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/64613/pexels-photo-64613.jpeg",
    description: "Galletas Marías clásicas para toda la familia",
    inStock: true,
    stock: 40,
    brand: "Bimbo",
    tags: ["marías", "clásicas", "familia", "tradicional"],
    rating: 4.4,
    reviewCount: 167,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-avena-bimbo",
    name: "Galletas de Avena Bimbo",
    price: 20,
    category: "panaderia-bimbo",
    subcategory: "galletas-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/64613/pexels-photo-64613.jpeg",
    description: "Galletas de avena con pasas",
    inStock: true,
    stock: 24,
    brand: "Bimbo",
    tags: ["avena", "pasas", "saludable", "fibra"],
    rating: 4.5,
    reviewCount: 98,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-coco-bimbo",
    name: "Galletas de Coco Bimbo",
    price: 19,
    category: "panaderia-bimbo",
    subcategory: "galletas-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/64613/pexels-photo-64613.jpeg",
    description: "Galletas con sabor a coco tropical",
    inStock: true,
    stock: 26,
    brand: "Bimbo",
    tags: ["coco", "tropical", "sabor", "dulces"],
    rating: 4.3,
    reviewCount: 87,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-integrales-bimbo",
    name: "Galletas Integrales Bimbo",
    price: 23,
    category: "panaderia-bimbo",
    subcategory: "galletas-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/64613/pexels-photo-64613.jpeg",
    description: "Galletas integrales ricas en fibra",
    inStock: true,
    stock: 20,
    brand: "Bimbo",
    tags: ["integrales", "fibra", "nutritivas", "saludable"],
    rating: 4.4,
    reviewCount: 76,
    deliveryTime: "15-20 min",
  },
  {
    id: "wafers-chocolate-bimbo",
    name: "Wafers de Chocolate Bimbo",
    price: 21,
    category: "panaderia-bimbo",
    subcategory: "galletas-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/64613/pexels-photo-64613.jpeg",
    description: "Obleas crujientes rellenas de chocolate",
    inStock: true,
    stock: 30,
    brand: "Bimbo",
    tags: ["wafers", "obleas", "chocolate", "crujientes"],
    rating: 4.6,
    reviewCount: 112,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-animalitos-bimbo",
    name: "Galletas Animalitos Bimbo",
    price: 17,
    category: "panaderia-bimbo",
    subcategory: "galletas-bimbo",
    aisle: "Pasillo 2",
    image: "https://images.pexels.com/photos/64613/pexels-photo-64613.jpeg",
    description: "Galletas en forma de animalitos para niños",
    inStock: true,
    stock: 35,
    brand: "Bimbo",
    tags: ["animalitos", "niños", "formas", "divertidas"],
    rating: 4.5,
    reviewCount: 145,
    deliveryTime: "15-20 min",
  },

  // Tortillas de harina (7 productos)
  {
    id: "tortillas-harina-bimbo",
    name: "Tortillas de Harina Bimbo",
    price: 28,
    category: "panaderia-bimbo",
    subcategory: "tortillas-bimbo",
    aisle: "Pasillo 2",
    image:
      "https://images.pexels.com/photos/16965368/pexels-photo-16965368.jpeg",
    description: "Tortillas de harina suaves y flexibles",
    inStock: true,
    stock: 40,
    brand: "Bimbo",
    tags: ["tortillas", "harina", "suaves", "flexibles"],
    rating: 4.5,
    reviewCount: 234,
    deliveryTime: "15-20 min",
  },
  {
    id: "tortillas-integrales-bimbo",
    name: "Tortillas Integrales Bimbo",
    price: 32,
    category: "panaderia-bimbo",
    subcategory: "tortillas-bimbo",
    aisle: "Pasillo 2",
    image:
      "https://images.pexels.com/photos/16965368/pexels-photo-16965368.jpeg",
    description: "Tortillas de harina integral ricas en fibra",
    inStock: true,
    stock: 28,
    brand: "Bimbo",
    tags: ["integrales", "fibra", "saludable", "nutritivas"],
    rating: 4.4,
    reviewCount: 156,
    deliveryTime: "15-20 min",
  },
  {
    id: "tortillas-grandes-bimbo",
    name: "Tortillas Grandes Bimbo",
    price: 35,
    category: "panaderia-bimbo",
    subcategory: "tortillas-bimbo",
    aisle: "Pasillo 2",
    image:
      "https://images.pexels.com/photos/16965368/pexels-photo-16965368.jpeg",
    description: "Tortillas grandes para burritos y quesadillas",
    inStock: true,
    stock: 32,
    brand: "Bimbo",
    tags: ["grandes", "burritos", "quesadillas", "versátiles"],
    rating: 4.6,
    reviewCount: 189,
    deliveryTime: "15-20 min",
  },
  {
    id: "tortillas-mini-bimbo",
    name: "Tortillas Mini Bimbo",
    price: 25,
    category: "panaderia-bimbo",
    subcategory: "tortillas-bimbo",
    aisle: "Pasillo 2",
    image:
      "https://images.pexels.com/photos/16965368/pexels-photo-16965368.jpeg",
    description: "Tortillas pequeñas para tacos y aperitivos",
    inStock: true,
    stock: 36,
    brand: "Bimbo",
    tags: ["mini", "tacos", "aperitivos", "pequeñas"],
    rating: 4.3,
    reviewCount: 123,
    deliveryTime: "15-20 min",
  },
  {
    id: "wraps-bimbo",
    name: "Wraps Bimbo",
    price: 38,
    category: "panaderia-bimbo",
    subcategory: "tortillas-bimbo",
    aisle: "Pasillo 2",
    image:
      "https://images.pexels.com/photos/16965368/pexels-photo-16965368.jpeg",
    description: "Wraps grandes para ensaladas y comidas",
    inStock: true,
    stock: 24,
    brand: "Bimbo",
    tags: ["wraps", "ensaladas", "comidas", "prácticos"],
    rating: 4.5,
    reviewCount: 87,
    deliveryTime: "15-20 min",
  },
  {
    id: "tortillas-espinaca-bimbo",
    name: "Tortillas de Espinaca Bimbo",
    price: 36,
    category: "panaderia-bimbo",
    subcategory: "tortillas-bimbo",
    aisle: "Pasillo 2",
    image:
      "https://images.pexels.com/photos/16965368/pexels-photo-16965368.jpeg",
    description: "Tortillas verdes con espinaca natural",
    inStock: true,
    stock: 20,
    brand: "Bimbo",
    tags: ["espinaca", "verdes", "natural", "nutritivas"],
    rating: 4.4,
    reviewCount: 76,
    deliveryTime: "15-20 min",
  },
  {
    id: "tortillas-tomate-bimbo",
    name: "Tortillas de Tomate Bimbo",
    price: 36,
    category: "panaderia-bimbo",
    subcategory: "tortillas-bimbo",
    aisle: "Pasillo 2",
    image:
      "https://images.pexels.com/photos/16965368/pexels-photo-16965368.jpeg",
    description: "Tortillas rojas con sabor a tomate",
    inStock: true,
    stock: 18,
    brand: "Bimbo",
    tags: ["tomate", "rojas", "sabor", "coloridas"],
    rating: 4.3,
    reviewCount: 64,
    deliveryTime: "15-20 min",
  },
];
