// CONTINUACIÓN DE PRODUCTOS - PASILLOS 3-15
// Este archivo contiene los productos adicionales para completar todas las categorías

import { Product } from "./data";

// Función para generar productos automáticamente para completar categorías
const generateProducts = (
  category: string,
  subcategory: string,
  aisle: string,
  baseId: string,
  baseName: string,
  basePrice: number,
  count: number,
): Product[] => {
  const products: Product[] = [];
  for (let i = 1; i <= count; i++) {
    products.push({
      id: `${baseId}-${i}`,
      name: `${baseName} ${i}`,
      price: basePrice + i * 2,
      category,
      subcategory,
      aisle,
      image:
        "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
      description: `${baseName} ${i} - Producto de calidad premium`,
      inStock: true,
      stock: Math.floor(Math.random() * 20) + 10,
      brand: "Marca Premium",
      tags: ["producto", "calidad", "premium"],
      rating: 4.0 + Math.random(),
      reviewCount: Math.floor(Math.random() * 100) + 20,
      deliveryTime: "15-20 min",
    });
  }
  return products;
};

export const additionalProducts: Product[] = [
  // PASILLO 3 - CARNICERÍA Y CREMERÍA (36 productos adicionales)
  ...generateProducts(
    "carniceria-cremeria",
    "carnes-rojas",
    "Pasillo 3",
    "carne-res",
    "Carne de Res",
    150,
    10,
  ),
  ...generateProducts(
    "carniceria-cremeria",
    "aves",
    "Pasillo 3",
    "pollo",
    "Pollo",
    80,
    8,
  ),
  ...generateProducts(
    "carniceria-cremeria",
    "pescados-mariscos",
    "Pasillo 3",
    "pescado",
    "Pescado",
    120,
    10,
  ),
  ...generateProducts(
    "carniceria-cremeria",
    "embutidos",
    "Pasillo 3",
    "embutido",
    "Embutido",
    45,
    6,
  ),
  ...generateProducts(
    "carniceria-cremeria",
    "carnes-frias",
    "Pasillo 3",
    "carne-fria",
    "Carne Fría",
    35,
    2,
  ),

  // PASILLO 4 - LÁCTEOS Y HUEVOS (42 productos)
  ...generateProducts(
    "lacteos-huevos",
    "leche",
    "Pasillo 4",
    "leche",
    "Leche",
    25,
    12,
  ),
  ...generateProducts(
    "lacteos-huevos",
    "quesos",
    "Pasillo 4",
    "queso",
    "Queso",
    45,
    15,
  ),
  ...generateProducts(
    "lacteos-huevos",
    "yogurt-probioticos",
    "Pasillo 4",
    "yogurt",
    "Yogurt",
    18,
    8,
  ),
  ...generateProducts(
    "lacteos-huevos",
    "mantequilla-margarina",
    "Pasillo 4",
    "mantequilla",
    "Mantequilla",
    32,
    5,
  ),
  ...generateProducts(
    "lacteos-huevos",
    "huevos",
    "Pasillo 4",
    "huevos",
    "Huevos",
    45,
    2,
  ),

  // PASILLO 5 - CONGELADOS (33 productos)
  ...generateProducts(
    "congelados",
    "helados-paletas",
    "Pasillo 5",
    "helado",
    "Helado",
    65,
    12,
  ),
  ...generateProducts(
    "congelados",
    "verduras-congeladas",
    "Pasillo 5",
    "verdura-congelada",
    "Verdura Congelada",
    28,
    8,
  ),
  ...generateProducts(
    "congelados",
    "carnes-pescados-congelados",
    "Pasillo 5",
    "carne-congelada",
    "Carne Congelada",
    95,
    6,
  ),
  ...generateProducts(
    "congelados",
    "comidas-preparadas",
    "Pasillo 5",
    "comida-preparada",
    "Comida Preparada",
    75,
    5,
  ),
  ...generateProducts(
    "congelados",
    "pizza-congelada",
    "Pasillo 5",
    "pizza-congelada",
    "Pizza Congelada",
    68,
    2,
  ),

  // PASILLO 6 - ABARROTES BÁSICOS (46 productos)
  ...generateProducts(
    "abarrotes-basicos",
    "arroz-granos",
    "Pasillo 6",
    "arroz",
    "Arroz",
    28,
    10,
  ),
  ...generateProducts(
    "abarrotes-basicos",
    "frijoles-legumbres",
    "Pasillo 6",
    "frijoles",
    "Frijoles",
    22,
    8,
  ),
  ...generateProducts(
    "abarrotes-basicos",
    "pasta-fideos",
    "Pasillo 6",
    "pasta",
    "Pasta",
    15,
    12,
  ),
  ...generateProducts(
    "abarrotes-basicos",
    "harina",
    "Pasillo 6",
    "harina",
    "Harina",
    25,
    6,
  ),
  ...generateProducts(
    "abarrotes-basicos",
    "azucar-endulzantes",
    "Pasillo 6",
    "azucar",
    "Azúcar",
    35,
    8,
  ),
  ...generateProducts(
    "abarrotes-basicos",
    "sal-especias",
    "Pasillo 6",
    "sal",
    "Sal y Especias",
    18,
    2,
  ),

  // PASILLO 7 - ENLATADOS Y CONSERVAS (39 productos)
  ...generateProducts(
    "enlatados-conservas",
    "atun-sardinas",
    "Pasillo 7",
    "atun",
    "Atún",
    28,
    8,
  ),
  ...generateProducts(
    "enlatados-conservas",
    "vegetales-enlatados",
    "Pasillo 7",
    "vegetal-enlatado",
    "Vegetal Enlatado",
    22,
    10,
  ),
  ...generateProducts(
    "enlatados-conservas",
    "frutas-almibar",
    "Pasillo 7",
    "fruta-almibar",
    "Fruta en Almíbar",
    35,
    6,
  ),
  ...generateProducts(
    "enlatados-conservas",
    "salsas-aderezos",
    "Pasillo 7",
    "salsa",
    "Salsa",
    25,
    8,
  ),
  ...generateProducts(
    "enlatados-conservas",
    "sopas-enlatadas",
    "Pasillo 7",
    "sopa-enlatada",
    "Sopa Enlatada",
    18,
    5,
  ),
  ...generateProducts(
    "enlatados-conservas",
    "chiles-encurtidos",
    "Pasillo 7",
    "chile-encurtido",
    "Chile Encurtido",
    15,
    2,
  ),

  // PASILLO 8 - ACEITES Y CONDIMENTOS (31 productos)
  ...generateProducts(
    "aceites-condimentos",
    "aceites-comestibles",
    "Pasillo 8",
    "aceite",
    "Aceite",
    45,
    8,
  ),
  ...generateProducts(
    "aceites-condimentos",
    "vinagres",
    "Pasillo 8",
    "vinagre",
    "Vinagre",
    25,
    4,
  ),
  ...generateProducts(
    "aceites-condimentos",
    "salsas-basicas",
    "Pasillo 8",
    "salsa-basica",
    "Salsa Básica",
    18,
    8,
  ),
  ...generateProducts(
    "aceites-condimentos",
    "condimentos-especias",
    "Pasillo 8",
    "condimento",
    "Condimento",
    22,
    6,
  ),
  ...generateProducts(
    "aceites-condimentos",
    "cubos-caldo",
    "Pasillo 8",
    "cubo-caldo",
    "Cubo de Caldo",
    8,
    3,
  ),
  ...generateProducts(
    "aceites-condimentos",
    "aderezos-ensalada",
    "Pasillo 8",
    "aderezo",
    "Aderezo",
    28,
    2,
  ),

  // PASILLO 9 - BEBIDAS (53 productos)
  ...generateProducts(
    "bebidas",
    "refrescos-sodas",
    "Pasillo 9",
    "refresco",
    "Refresco",
    18,
    15,
  ),
  ...generateProducts(
    "bebidas",
    "jugos-envasados",
    "Pasillo 9",
    "jugo-envasado",
    "Jugo Envasado",
    25,
    12,
  ),
  ...generateProducts(
    "bebidas",
    "agua-embotellada",
    "Pasillo 9",
    "agua",
    "Agua",
    12,
    8,
  ),
  ...generateProducts(
    "bebidas",
    "bebidas-energeticas",
    "Pasillo 9",
    "bebida-energetica",
    "Bebida Energética",
    28,
    6,
  ),
  ...generateProducts(
    "bebidas",
    "te-cafe",
    "Pasillo 9",
    "te-cafe",
    "Té y Café",
    35,
    10,
  ),
  ...generateProducts(
    "bebidas",
    "bebidas-deportivas",
    "Pasillo 9",
    "bebida-deportiva",
    "Bebida Deportiva",
    22,
    2,
  ),

  // PASILLO 10 - BOTANAS Y DULCES (41 productos)
  ...generateProducts(
    "botanas-dulces",
    "papas-frituras",
    "Pasillo 10",
    "papas",
    "Papas",
    18,
    12,
  ),
  ...generateProducts(
    "botanas-dulces",
    "galletas-saladas",
    "Pasillo 10",
    "galleta-salada",
    "Galleta Salada",
    22,
    8,
  ),
  ...generateProducts(
    "botanas-dulces",
    "chocolates-dulces",
    "Pasillo 10",
    "chocolate",
    "Chocolate",
    15,
    10,
  ),
  ...generateProducts(
    "botanas-dulces",
    "chicles-caramelos",
    "Pasillo 10",
    "chicle",
    "Chicle",
    8,
    6,
  ),
  ...generateProducts(
    "botanas-dulces",
    "frutos-secos",
    "Pasillo 10",
    "fruto-seco",
    "Fruto Seco",
    35,
    3,
  ),
  ...generateProducts(
    "botanas-dulces",
    "palomitas",
    "Pasillo 10",
    "palomitas",
    "Palomitas",
    25,
    2,
  ),

  // PASILLO 11 - DESAYUNO Y CEREALES (33 productos)
  ...generateProducts(
    "desayuno-cereales",
    "cereales-desayuno",
    "Pasillo 11",
    "cereal",
    "Cereal",
    45,
    12,
  ),
  ...generateProducts(
    "desayuno-cereales",
    "avena-granola",
    "Pasillo 11",
    "avena",
    "Avena",
    35,
    6,
  ),
  ...generateProducts(
    "desayuno-cereales",
    "miel-mermeladas",
    "Pasillo 11",
    "miel",
    "Miel",
    28,
    8,
  ),
  ...generateProducts(
    "desayuno-cereales",
    "jarabe-hotcakes",
    "Pasillo 11",
    "jarabe",
    "Jarabe",
    32,
    3,
  ),
  ...generateProducts(
    "desayuno-cereales",
    "barras-nutritivas",
    "Pasillo 11",
    "barra",
    "Barra Nutritiva",
    18,
    2,
  ),
  ...generateProducts(
    "desayuno-cereales",
    "leches-polvo",
    "Pasillo 11",
    "leche-polvo",
    "Leche en Polvo",
    85,
    2,
  ),

  // PASILLO 12 - CUIDADO PERSONAL (34 productos)
  ...generateProducts(
    "cuidado-personal",
    "shampoo-acondicionador",
    "Pasillo 12",
    "shampoo",
    "Champú",
    45,
    8,
  ),
  ...generateProducts(
    "cuidado-personal",
    "jabones-corporales",
    "Pasillo 12",
    "jabon",
    "Jabón",
    22,
    6,
  ),
  ...generateProducts(
    "cuidado-personal",
    "pasta-dental",
    "Pasillo 12",
    "pasta-dental",
    "Pasta Dental",
    25,
    5,
  ),
  ...generateProducts(
    "cuidado-personal",
    "desodorantes",
    "Pasillo 12",
    "desodorante",
    "Desodorante",
    28,
    6,
  ),
  ...generateProducts(
    "cuidado-personal",
    "productos-femeninos",
    "Pasillo 12",
    "producto-femenino",
    "Producto Femenino",
    32,
    5,
  ),
  ...generateProducts(
    "cuidado-personal",
    "medicinas-basicas",
    "Pasillo 12",
    "medicina",
    "Medicina",
    15,
    4,
  ),

  // PASILLO 13 - LIMPIEZA DEL HOGAR (31 productos)
  ...generateProducts(
    "limpieza-hogar",
    "detergentes-ropa",
    "Pasillo 13",
    "detergente",
    "Detergente",
    35,
    8,
  ),
  ...generateProducts(
    "limpieza-hogar",
    "limpiadores-multiusos",
    "Pasillo 13",
    "limpiador",
    "Limpiador",
    28,
    6,
  ),
  ...generateProducts(
    "limpieza-hogar",
    "papel-higienico",
    "Pasillo 13",
    "papel",
    "Papel",
    22,
    6,
  ),
  ...generateProducts(
    "limpieza-hogar",
    "productos-trastes",
    "Pasillo 13",
    "producto-trastes",
    "Producto para Trastes",
    18,
    5,
  ),
  ...generateProducts(
    "limpieza-hogar",
    "desinfectantes",
    "Pasillo 13",
    "desinfectante",
    "Desinfectante",
    25,
    3,
  ),
  ...generateProducts(
    "limpieza-hogar",
    "bolsas-basura",
    "Pasillo 13",
    "bolsa-basura",
    "Bolsa de Basura",
    15,
    3,
  ),

  // PASILLO 14 - BEBIDAS ALCOHÓLICAS (38 productos)
  ...generateProducts(
    "bebidas-alcoholicas",
    "cervezas",
    "Pasillo 14",
    "cerveza",
    "Cerveza",
    18,
    15,
  ),
  ...generateProducts(
    "bebidas-alcoholicas",
    "vinos",
    "Pasillo 14",
    "vino",
    "Vino",
    85,
    10,
  ),
  ...generateProducts(
    "bebidas-alcoholicas",
    "licores-destilados",
    "Pasillo 14",
    "licor",
    "Licor",
    150,
    8,
  ),
  ...generateProducts(
    "bebidas-alcoholicas",
    "mezcal-tequila",
    "Pasillo 14",
    "tequila",
    "Tequila",
    200,
    3,
  ),
  ...generateProducts(
    "bebidas-alcoholicas",
    "whisky-ron",
    "Pasillo 14",
    "whisky",
    "Whisky",
    300,
    1,
  ),
  ...generateProducts(
    "bebidas-alcoholicas",
    "aperitivos",
    "Pasillo 14",
    "aperitivo",
    "Aperitivo",
    125,
    1,
  ),

  // PASILLO 15 - PRODUCTOS PARA BEBÉS (24 productos)
  ...generateProducts(
    "productos-bebes",
    "pañales-toallitas",
    "Pasillo 15",
    "panal",
    "Pañal",
    85,
    8,
  ),
  ...generateProducts(
    "productos-bebes",
    "formulas-leches",
    "Pasillo 15",
    "formula",
    "Fórmula",
    125,
    6,
  ),
  ...generateProducts(
    "productos-bebes",
    "comidas-bebes",
    "Pasillo 15",
    "comida-bebe",
    "Comida para Bebé",
    28,
    8,
  ),
  ...generateProducts(
    "productos-bebes",
    "biberones-accesorios",
    "Pasillo 15",
    "biberon",
    "Biberón",
    45,
    2,
  ),
];

export default additionalProducts;
