export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  category: string;
  subcategory?: string;
  aisle?: string;
  image: string;
  description: string;
  inStock: boolean;
  stock: number;
  brand?: string;
  tags: string[];
  rating: number;
  reviewCount: number;
  isNew?: boolean;
  isOffer?: boolean;
  deliveryTime: string;
  barcode?: string;
  organic?: boolean;
}

export interface Subcategory {
  id: string;
  name: string;
  icon: string;
  productCount: number;
}

export interface Category {
  id: string;
  name: string;
  image: string;
  icon: string;
  color: string;
  productCount: number;
  aisle: number;
  description: string;
  subcategories: Subcategory[];
}

export const categories: Category[] = [
  {
    id: "frutas-verduras",
    name: "Frutas y Verduras",
    image:
      "https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=400&q=80",
    icon: "🥬",
    color: "bg-fresh-500",
    productCount: 75,
    aisle: 1,
    description: "Productos frescos del día",
    subcategories: [
      {
        id: "frutas-frescas",
        name: "Frutas frescas",
        icon: "🍎",
        productCount: 25,
      },
      { id: "verduras", name: "Verduras", icon: "🥕", productCount: 20 },
      {
        id: "hierbas-aromaticas",
        name: "Hierbas aromáticas",
        icon: "🌿",
        productCount: 12,
      },
      {
        id: "productos-organicos",
        name: "Productos orgánicos",
        icon: "🌱",
        productCount: 15,
      },
      {
        id: "jugos-naturales",
        name: "Jugos naturales refrigerados",
        icon: "🥤",
        productCount: 8,
      },
    ],
  },
  {
    id: "panaderia-bimbo",
    name: "Panadería Bimbo",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
    icon: "🍞",
    color: "bg-yellow-400",
    productCount: 45,
    aisle: 2,
    description: "Productos Bimbo frescos y de calidad",
    subcategories: [
      {
        id: "pan-de-caja",
        name: "Pan de caja",
        icon: "🍞",
        productCount: 12,
      },
      {
        id: "pan-tostado",
        name: "Pan tostado y integral",
        icon: "🍞",
        productCount: 8,
      },
      {
        id: "pasteles-bimbo",
        name: "Pasteles y roles",
        icon: "🧁",
        productCount: 10,
      },
      {
        id: "galletas-bimbo",
        name: "Galletas y cookies",
        icon: "🍪",
        productCount: 8,
      },
      {
        id: "tortillas-bimbo",
        name: "Tortillas de harina",
        icon: "🌮",
        productCount: 7,
      },
    ],
  },
  {
    id: "carniceria-charcuteria",
    name: "Carnicería y Charcutería",
    image:
      "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=400&q=80",
    icon: "🥩",
    color: "bg-red-500",
    productCount: 38,
    aisle: 3,
    description: "Carnes frescas y embutidos selectos",
    subcategories: [
      {
        id: "carnes-rojas",
        name: "Carnes rojas",
        icon: "🥩",
        productCount: 12,
      },
      { id: "aves", name: "Aves", icon: "🐔", productCount: 8 },
      {
        id: "pescados-mariscos",
        name: "Pescados y mariscos frescos",
        icon: "🐟",
        productCount: 10,
      },
      { id: "embutidos", name: "Embutidos", icon: "🌭", productCount: 6 },
      { id: "carnes-frias", name: "Carnes frías", icon: "🥓", productCount: 8 },
    ],
  },
  {
    id: "lacteos-huevos",
    name: "Lácteos y Huevos",
    image:
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=400&q=80",
    icon: "🥛",
    color: "bg-orange-400",
    productCount: 42,
    aisle: 4,
    description: "Productos lácteos frescos diarios",
    subcategories: [
      { id: "leche", name: "Leche", icon: "🥛", productCount: 12 },
      { id: "quesos", name: "Quesos", icon: "🧀", productCount: 15 },
      {
        id: "yogurt-fermentados",
        name: "Yogurt y productos fermentados",
        icon: "🥄",
        productCount: 8,
      },
      {
        id: "mantequilla-margarina",
        name: "Mantequilla y margarina",
        icon: "🧈",
        productCount: 5,
      },
      { id: "huevos", name: "Huevos de gallina", icon: "🥚", productCount: 4 },
      {
        id: "crema-cocinar",
        name: "Crema y productos para cocinar",
        icon: "🥣",
        productCount: 6,
      },
    ],
  },
  {
    id: "congelados",
    name: "Congelados",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    icon: "🧊",
    color: "bg-mint-400",
    productCount: 35,
    aisle: 5,
    description: "Productos congelados y helados",
    subcategories: [
      {
        id: "helados-paletas",
        name: "Helados y paletas",
        icon: "🍦",
        productCount: 12,
      },
      {
        id: "verduras-congeladas",
        name: "Verduras congeladas",
        icon: "🥶",
        productCount: 8,
      },
      {
        id: "carnes-pescados-congelados",
        name: "Carnes y pescados congelados",
        icon: "🐟",
        productCount: 6,
      },
      {
        id: "comidas-preparadas",
        name: "Comidas preparadas congeladas",
        icon: "🍽️",
        productCount: 5,
      },
      {
        id: "pizza-congelada",
        name: "Pizza congelada",
        icon: "🍕",
        productCount: 4,
      },
      {
        id: "postres-congelados",
        name: "Postres congelados",
        icon: "🧁",
        productCount: 3,
      },
    ],
  },
  {
    id: "abarrotes-basicos",
    name: "Abarrotes Básicos",
    image:
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80",
    icon: "🌾",
    color: "bg-violet-400",
    productCount: 48,
    aisle: 6,
    description: "Productos básicos para la despensa",
    subcategories: [
      {
        id: "arroz-granos",
        name: "Arroz y granos",
        icon: "🍚",
        productCount: 10,
      },
      {
        id: "frijoles-legumbres",
        name: "Frijoles y legumbres",
        icon: "🫘",
        productCount: 8,
      },
      {
        id: "pasta-fideos",
        name: "Pasta y fideos",
        icon: "🍝",
        productCount: 12,
      },
      {
        id: "harina",
        name: "Harina y harinas especiales",
        icon: "🌾",
        productCount: 6,
      },
      {
        id: "azucar-endulzantes",
        name: "Azúcar y endulzantes",
        icon: "🍯",
        productCount: 8,
      },
      {
        id: "sal-especias",
        name: "Sal y especias",
        icon: "🧂",
        productCount: 10,
      },
    ],
  },
  {
    id: "enlatados-conservas",
    name: "Enlatados y Conservas",
    image:
      "https://images.unsplash.com/photo-1553909489-cd47e0ef937f?auto=format&fit=crop&w=400&q=80",
    icon: "🥫",
    color: "bg-sky-600",
    productCount: 40,
    aisle: 7,
    description: "Productos enlatados y conservas",
    subcategories: [
      {
        id: "atun-sardinas",
        name: "Atún y sardinas",
        icon: "🐟",
        productCount: 8,
      },
      {
        id: "vegetales-enlatados",
        name: "Vegetales enlatados",
        icon: "🥫",
        productCount: 10,
      },
      {
        id: "frutas-almibar",
        name: "Frutas en almíbar",
        icon: "🍑",
        productCount: 6,
      },
      {
        id: "salsas-aderezos",
        name: "Salsas y aderezos",
        icon: "🍅",
        productCount: 8,
      },
      {
        id: "sopas-enlatadas",
        name: "Sopas enlatadas",
        icon: "🍲",
        productCount: 5,
      },
      {
        id: "chiles-encurtidos",
        name: "Chiles y encurtidos",
        icon: "🌶️",
        productCount: 6,
      },
    ],
  },
  {
    id: "aceites-condimentos",
    name: "Aceites y Condimentos",
    image:
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80",
    icon: "🫒",
    color: "bg-mint-600",
    productCount: 32,
    aisle: 8,
    description: "Aceites, vinagres y condimentos",
    subcategories: [
      {
        id: "aceites-comestibles",
        name: "Aceites comestibles",
        icon: "🫒",
        productCount: 8,
      },
      { id: "vinagres", name: "Vinagres", icon: "🍶", productCount: 4 },
      {
        id: "salsas-basicas",
        name: "Salsas básicas",
        icon: "🥫",
        productCount: 8,
      },
      {
        id: "condimentos-especias",
        name: "Condimentos y especias",
        icon: "🧂",
        productCount: 6,
      },
      {
        id: "cubos-caldo",
        name: "Cubos de caldo",
        icon: "🧊",
        productCount: 3,
      },
      {
        id: "aderezos-ensalada",
        name: "Aderezos para ensalada",
        icon: "🥗",
        productCount: 5,
      },
    ],
  },
  {
    id: "bebidas",
    name: "Bebidas",
    image:
      "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=400&q=80",
    icon: "🥤",
    color: "bg-sky-500",
    productCount: 55,
    aisle: 9,
    description: "Bebidas refrescantes y calientes",
    subcategories: [
      {
        id: "refrescos-sodas",
        name: "Refrescos y sodas",
        icon: "🥤",
        productCount: 15,
      },
      {
        id: "jugos-envasados",
        name: "Jugos envasados",
        icon: "🧃",
        productCount: 12,
      },
      {
        id: "agua-purificada",
        name: "Agua purificada",
        icon: "💧",
        productCount: 8,
      },
      {
        id: "bebidas-deportivas",
        name: "Bebidas deportivas",
        icon: "⚡",
        productCount: 6,
      },
      { id: "te-cafe", name: "Té y café", icon: "☕", productCount: 10 },
      {
        id: "bebidas-energizantes",
        name: "Bebidas energizantes",
        icon: "🔋",
        productCount: 5,
      },
    ],
  },
  {
    id: "botanas-dulces",
    name: "Botanas y Dulces",
    image:
      "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=400&q=80",
    icon: "🍿",
    color: "bg-violet-500",
    productCount: 44,
    aisle: 10,
    description: "Snacks y dulces para todos",
    subcategories: [
      {
        id: "papas-frituras",
        name: "Papas fritas y frituras",
        icon: "🍟",
        productCount: 12,
      },
      {
        id: "galletas-saladas",
        name: "Galletas saladas",
        icon: "🍘",
        productCount: 8,
      },
      {
        id: "chocolates-dulces",
        name: "Chocolates y dulces",
        icon: "🍫",
        productCount: 10,
      },
      {
        id: "chicles-caramelos",
        name: "Chicles y caramelos",
        icon: "🍭",
        productCount: 6,
      },
      { id: "frutos-secos", name: "Frutos secos", icon: "🥜", productCount: 5 },
      { id: "palomitas", name: "Palomitas", icon: "🍿", productCount: 4 },
    ],
  },
  {
    id: "desayuno-cereales",
    name: "Desayuno y Cereales",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    icon: "🥣",
    color: "bg-mint-500",
    productCount: 36,
    aisle: 11,
    description: "Todo para un desayuno completo",
    subcategories: [
      {
        id: "cereales-desayuno",
        name: "Cereales para desayuno",
        icon: "���",
        productCount: 12,
      },
      {
        id: "avena-granola",
        name: "Avena y granola",
        icon: "🌾",
        productCount: 6,
      },
      {
        id: "miel-mermeladas",
        name: "Miel y mermeladas",
        icon: "🍯",
        productCount: 8,
      },
      {
        id: "jarabe-hotcakes",
        name: "Jarabe para hot cakes",
        icon: "🥞",
        productCount: 3,
      },
      {
        id: "barras-nutritivas",
        name: "Barras nutritivas",
        icon: "🍫",
        productCount: 5,
      },
      {
        id: "leches-polvo",
        name: "Leches en polvo",
        icon: "🥛",
        productCount: 4,
      },
    ],
  },
  {
    id: "cuidado-personal",
    name: "Cuidado Personal",
    image:
      "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=400&q=80",
    icon: "🧼",
    color: "bg-violet-400",
    productCount: 38,
    aisle: 12,
    description: "Productos de higiene personal",
    subcategories: [
      {
        id: "shampoo-acondicionador",
        name: "Champú y acondicionador",
        icon: "����",
        productCount: 8,
      },
      {
        id: "jabones-corporales",
        name: "Jabones corporales",
        icon: "🧼",
        productCount: 6,
      },
      {
        id: "pasta-dental",
        name: "Pasta dental y cepillos",
        icon: "🦷",
        productCount: 5,
      },
      { id: "desodorantes", name: "Desodorantes", icon: "💨", productCount: 6 },
      {
        id: "productos-femeninos",
        name: "Productos femeninos",
        icon: "🌸",
        productCount: 5,
      },
      {
        id: "medicinas-basicas",
        name: "Medicinas básicas",
        icon: "💊",
        productCount: 8,
      },
    ],
  },
  {
    id: "limpieza-hogar",
    name: "Limpieza del Hogar",
    image:
      "https://images.unsplash.com/photo-1563453392212-326f5e854473?auto=format&fit=crop&w=400&q=80",
    icon: "🧽",
    color: "bg-sky-400",
    productCount: 35,
    aisle: 13,
    description: "Productos para el hogar",
    subcategories: [
      {
        id: "detergentes-ropa",
        name: "Detergentes para ropa",
        icon: "👕",
        productCount: 8,
      },
      {
        id: "limpiadores-multiusos",
        name: "Limpiadores multiusos",
        icon: "🧽",
        productCount: 6,
      },
      {
        id: "papel-higienico",
        name: "Papel higiénico y servilletas",
        icon: "🧻",
        productCount: 6,
      },
      {
        id: "productos-trastes",
        name: "Productos para trastes",
        icon: "🍽️",
        productCount: 5,
      },
      {
        id: "desinfectantes",
        name: "Desinfectantes",
        icon: "🦠",
        productCount: 5,
      },
      {
        id: "bolsas-basura",
        name: "Bolsas de basura",
        icon: "🗑️",
        productCount: 5,
      },
    ],
  },
  {
    id: "bebidas-alcoholicas",
    name: "Bebidas Alcohólicas",
    image:
      "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=400&q=80",
    icon: "🍺",
    color: "bg-violet-600",
    productCount: 42,
    aisle: 14,
    description: "Solo para mayores de edad",
    subcategories: [
      {
        id: "cervezas",
        name: "Cervezas nacionales e importadas",
        icon: "🍺",
        productCount: 15,
      },
      {
        id: "vinos",
        name: "Vinos tintos, blancos y rosados",
        icon: "🍷",
        productCount: 10,
      },
      {
        id: "licores-destilados",
        name: "Licores y destilados",
        icon: "🥃",
        productCount: 8,
      },
      {
        id: "mezcal-tequila",
        name: "Mezcal y tequila",
        icon: "🇲🇽",
        productCount: 5,
      },
      { id: "whisky-ron", name: "Whisky y ron", icon: "🥃", productCount: 3 },
      { id: "aperitivos", name: "Aperitivos", icon: "🍸", productCount: 4 },
    ],
  },
  {
    id: "productos-bebes",
    name: "Productos para Bebés",
    image:
      "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=400&q=80",
    icon: "👶",
    color: "bg-mint-400",
    productCount: 32,
    aisle: 15,
    description: "Todo para el cuidado del bebé",
    subcategories: [
      {
        id: "panales-desechables",
        name: "Pañales desechables",
        icon: "👶",
        productCount: 8,
      },
      {
        id: "formulas-lacteas",
        name: "Fórmulas lácteas",
        icon: "🍼",
        productCount: 6,
      },
      {
        id: "papillas-infantiles",
        name: "Papillas y alimentos infantiles",
        icon: "🥄",
        productCount: 8,
      },
      {
        id: "biberones-chupones",
        name: "Biberones y chupones",
        icon: "🍼",
        productCount: 4,
      },
      {
        id: "higiene-bebe",
        name: "Productos de higiene para bebé",
        icon: "🧼",
        productCount: 5,
      },
      {
        id: "juguetes-basicos",
        name: "Juguetes básicos",
        icon: "🧸",
        productCount: 3,
      },
    ],
  },
];

export const storeHours = {
  open: "09:00",
  close: "17:00",
  timezone: "America/Mexico_City",
  days: [
    "Lunes",
    "Martes",
    "Miércoles",
    "Jueves",
    "Viernes",
    "Sábado",
    "Domingo",
  ],
};

export const products: Product[] = [
  // PASILLO 1 - FRUTAS Y VERDURAS (75 productos)
  // Frutas frescas (25 productos)
  {
    id: "manzanas-rojas",
    name: "Manzanas Rojas kg",
    price: 45,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description:
      "Manzanas rojas frescas y crujientes, ideales para snacks saludables",
    inStock: true,
    stock: 50,
    brand: "Frutos del Valle",
    tags: ["fruta", "fresco", "saludable", "orgánico"],
    rating: 4.7,
    reviewCount: 89,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "platanos-kg",
    name: "Plátanos kg",
    price: 24,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Plátanos frescos y dulces, ricos en potasio",
    inStock: true,
    stock: 30,
    brand: "Frutos del Valle",
    tags: ["fruta", "fresco", "potasio", "saludable"],
    rating: 4.6,
    reviewCount: 92,
    deliveryTime: "15-20 min",
  },
  {
    id: "naranjas-kg",
    name: "Naranjas kg",
    price: 28,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Naranjas jugosas valencia, perfectas para jugo",
    inStock: true,
    stock: 40,
    brand: "Frutos del Valle",
    tags: ["fruta", "cítrico", "vitamina C", "jugo"],
    rating: 4.5,
    reviewCount: 78,
    deliveryTime: "15-20 min",
  },
  {
    id: "fresas-kg",
    name: "Fresas kg",
    price: 85,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Fresas dulces y frescas de temporada",
    inStock: true,
    stock: 15,
    brand: "Frutos del Valle",
    tags: ["fruta", "dulce", "temporada", "antioxidantes"],
    rating: 4.8,
    reviewCount: 156,
    deliveryTime: "15-20 min",
  },
  {
    id: "uvas-verdes",
    name: "Uvas Verdes kg",
    price: 68,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Uvas verdes sin semilla, dulces y refrescantes",
    inStock: true,
    stock: 25,
    brand: "Frutos del Valle",
    tags: ["fruta", "sin semilla", "dulce", "refrescante"],
    rating: 4.6,
    reviewCount: 67,
    deliveryTime: "15-20 min",
  },
  {
    id: "pina-kg",
    name: "Piña kg",
    price: 35,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Piña madura y dulce, perfecta para postres",
    inStock: true,
    stock: 20,
    brand: "Frutos del Valle",
    tags: ["fruta", "tropical", "dulce", "vitamina C"],
    rating: 4.7,
    reviewCount: 89,
    deliveryTime: "15-20 min",
  },
  {
    id: "mango-kg",
    name: "Mango Ataulfo kg",
    price: 52,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Mango ataulfo maduro, cremoso y dulce",
    inStock: true,
    stock: 18,
    brand: "Frutos del Valle",
    tags: ["fruta", "tropical", "cremoso", "dulce"],
    rating: 4.9,
    reviewCount: 134,
    deliveryTime: "15-20 min",
  },
  {
    id: "papaya-kg",
    name: "Papaya kg",
    price: 32,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Papaya madura, ideal para digestión",
    inStock: true,
    stock: 12,
    brand: "Frutos del Valle",
    tags: ["fruta", "tropical", "digestión", "vitaminas"],
    rating: 4.4,
    reviewCount: 56,
    deliveryTime: "15-20 min",
  },
  {
    id: "sandia-kg",
    name: "Sandía kg",
    price: 18,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Sandía dulce y refrescante para el calor",
    inStock: true,
    stock: 8,
    brand: "Frutos del Valle",
    tags: ["fruta", "refrescante", "verano", "hidratante"],
    rating: 4.5,
    reviewCount: 73,
    deliveryTime: "15-20 min",
  },
  {
    id: "melon-kg",
    name: "Melón kg",
    price: 28,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Melón cantaloupe maduro y aromático",
    inStock: true,
    stock: 15,
    brand: "Frutos del Valle",
    tags: ["fruta", "aromático", "dulce", "refrescante"],
    rating: 4.3,
    reviewCount: 45,
    deliveryTime: "15-20 min",
  },
  {
    id: "peras-kg",
    name: "Peras kg",
    price: 55,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Peras anjou maduras y jugosas",
    inStock: true,
    stock: 22,
    brand: "Frutos del Valle",
    tags: ["fruta", "jugosa", "fibra", "dulce"],
    rating: 4.4,
    reviewCount: 65,
    deliveryTime: "15-20 min",
  },
  {
    id: "durazno-kg",
    name: "Duraznos kg",
    price: 58,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Duraznos maduros de temporada",
    inStock: true,
    stock: 16,
    brand: "Frutos del Valle",
    tags: ["fruta", "temporada", "jugoso", "dulce"],
    rating: 4.6,
    reviewCount: 84,
    deliveryTime: "15-20 min",
  },
  {
    id: "kiwi-kg",
    name: "Kiwi kg",
    price: 85,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Kiwi verde rico en vitamina C",
    inStock: true,
    stock: 24,
    brand: "Frutos del Valle",
    tags: ["fruta", "vitamina C", "exótico", "dulce"],
    rating: 4.6,
    reviewCount: 71,
    deliveryTime: "15-20 min",
  },
  {
    id: "limones-kg",
    name: "Limones kg",
    price: 22,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Limones verdes mexicanos, muy jugosos",
    inStock: true,
    stock: 35,
    brand: "Frutos del Valle",
    tags: ["cítrico", "ácido", "vitamina C", "mexicano"],
    rating: 4.7,
    reviewCount: 98,
    deliveryTime: "15-20 min",
  },
  {
    id: "toronja-kg",
    name: "Toronja kg",
    price: 38,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Toronja roja jugosa y refrescante",
    inStock: true,
    stock: 28,
    brand: "Frutos del Valle",
    tags: ["cítrico", "vitamina C", "amarga", "diurética"],
    rating: 4.3,
    reviewCount: 54,
    deliveryTime: "15-20 min",
  },
  {
    id: "mandarina-kg",
    name: "Mandarinas kg",
    price: 42,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Mandarinas dulces fáciles de pelar",
    inStock: true,
    stock: 30,
    brand: "Frutos del Valle",
    tags: ["cítrico", "dulce", "fácil pelar", "niños"],
    rating: 4.8,
    reviewCount: 112,
    deliveryTime: "15-20 min",
  },
  {
    id: "coco-pieza",
    name: "Coco pieza",
    price: 35,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Coco fresco para agua y pulpa",
    inStock: true,
    stock: 12,
    brand: "Frutos del Valle",
    tags: ["tropical", "agua", "pulpa", "refrescante"],
    rating: 4.5,
    reviewCount: 67,
    deliveryTime: "15-20 min",
  },
  {
    id: "granada-kg",
    name: "Granada kg",
    price: 85,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Granada roja rica en antioxidantes",
    inStock: true,
    stock: 8,
    brand: "Frutos del Valle",
    tags: ["fruta", "antioxidantes", "exótica", "saludable"],
    rating: 4.7,
    reviewCount: 89,
    deliveryTime: "15-20 min",
  },
  {
    id: "ciruela-kg",
    name: "Ciruelas kg",
    price: 48,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Ciruelas rojas dulces y jugosas",
    inStock: true,
    stock: 14,
    brand: "Frutos del Valle",
    tags: ["dulce", "jugosa", "temporada", "fibra"],
    rating: 4.5,
    reviewCount: 38,
    deliveryTime: "15-20 min",
  },
  {
    id: "guayaba-kg",
    name: "Guayabas kg",
    price: 48,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Guayabas maduras muy aromáticas",
    inStock: true,
    stock: 10,
    brand: "Frutos del Valle",
    tags: ["aromática", "vitamina C", "tropical", "dulce"],
    rating: 4.3,
    reviewCount: 29,
    deliveryTime: "15-20 min",
  },
  {
    id: "mamey-kg",
    name: "Mamey kg",
    price: 78,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Mamey maduro cremoso y dulce",
    inStock: true,
    stock: 6,
    brand: "Frutos del Valle",
    tags: ["tropical", "cremoso", "dulce", "vitaminas"],
    rating: 4.7,
    reviewCount: 51,
    deliveryTime: "15-20 min",
  },
  {
    id: "jicama-kg",
    name: "Jícama kg",
    price: 32,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Jícama fresca y crujiente",
    inStock: true,
    stock: 18,
    brand: "Frutos del Valle",
    tags: ["crujiente", "fibra", "bajo calórías", "refrescante"],
    rating: 4.2,
    reviewCount: 35,
    deliveryTime: "15-20 min",
  },
  {
    id: "tuna-kg",
    name: "Tunas kg",
    price: 38,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Tunas rojas dulces y refrescantes",
    inStock: true,
    stock: 15,
    brand: "Frutos del Valle",
    tags: ["cactus", "dulce", "mexicana", "refrescante"],
    rating: 4.4,
    reviewCount: 42,
    deliveryTime: "15-20 min",
  },
  {
    id: "zapote-kg",
    name: "Zapote kg",
    price: 58,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Zapote negro maduro y dulce",
    inStock: true,
    stock: 8,
    brand: "Frutos del Valle",
    tags: ["tropical", "dulce", "cremoso", "tradicional"],
    rating: 4.5,
    reviewCount: 27,
    deliveryTime: "15-20 min",
  },
  {
    id: "chicozapote-kg",
    name: "Chicozapote kg",
    price: 65,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Chicozapote maduro muy dulce",
    inStock: true,
    stock: 5,
    brand: "Frutos del Valle",
    tags: ["tropical", "muy dulce", "cremoso", "exótico"],
    rating: 4.6,
    reviewCount: 19,
    deliveryTime: "15-20 min",
  },

  // Verduras (20 productos)
  {
    id: "lechuga-pieza",
    name: "Lechuga Romana pieza",
    price: 18,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1556801712-102246837aa7?auto=format&fit=crop&w=400&q=80",
    description: "Lechuga romana fresca para ensaladas",
    inStock: true,
    stock: 25,
    brand: "Verduras Frescas",
    tags: ["ensalada", "fresco", "crujiente", "vitaminas"],
    rating: 4.3,
    reviewCount: 67,
    deliveryTime: "15-20 min",
  },
  {
    id: "tomate-kg",
    name: "Tomate Saladette kg",
    price: 35,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1592841200221-21e1c7d95b6b?auto=format&fit=crop&w=400&q=80",
    description: "Tomate saladette fresco para ensaladas",
    inStock: true,
    stock: 40,
    brand: "Verduras Frescas",
    tags: ["ensalada", "fresco", "jugoso", "vitamina C"],
    rating: 4.5,
    reviewCount: 89,
    deliveryTime: "15-20 min",
  },
  {
    id: "cebolla-kg",
    name: "Cebolla Blanca kg",
    price: 28,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=400&q=80",
    description: "Cebolla blanca fresca para cocinar",
    inStock: true,
    stock: 50,
    brand: "Verduras Frescas",
    tags: ["cocina", "básico", "aromático", "versátil"],
    rating: 4.4,
    reviewCount: 78,
    deliveryTime: "15-20 min",
  },
  {
    id: "zanahoria-kg",
    name: "Zanahoria kg",
    price: 22,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=400&q=80",
    description: "Zanahorias frescas ricas en vitamina A",
    inStock: true,
    stock: 35,
    brand: "Verduras Frescas",
    tags: ["vitamina A", "crujiente", "dulce", "saludable"],
    rating: 4.6,
    reviewCount: 92,
    deliveryTime: "15-20 min",
  },
  {
    id: "pepino-kg",
    name: "Pepino kg",
    price: 25,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?auto=format&fit=crop&w=400&q=80",
    description: "Pepinos frescos y crujientes",
    inStock: true,
    stock: 30,
    brand: "Verduras Frescas",
    tags: ["refrescante", "crujiente", "hidratante", "ensalada"],
    rating: 4.3,
    reviewCount: 56,
    deliveryTime: "15-20 min",
  },
  // Continuando con más verduras...
  {
    id: "papa-kg",
    name: "Papa Blanca kg",
    price: 24,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=400&q=80",
    description: "Papas blancas frescas para guisos",
    inStock: true,
    stock: 60,
    brand: "Verduras Frescas",
    tags: ["básico", "versátil", "carbohidratos", "cocina"],
    rating: 4.5,
    reviewCount: 134,
    deliveryTime: "15-20 min",
  },
  {
    id: "calabaza-kg",
    name: "Calabaza kg",
    price: 18,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Calabaza italiana fresca y tierna",
    inStock: true,
    stock: 20,
    brand: "Verduras Frescas",
    tags: ["tierna", "vitaminas", "bajo calórico", "versátil"],
    rating: 4.2,
    reviewCount: 45,
    deliveryTime: "15-20 min",
  },
  {
    id: "chayote-kg",
    name: "Chayote kg",
    price: 32,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Chayotes frescos ideales para guisos",
    inStock: true,
    stock: 25,
    brand: "Verduras Frescas",
    tags: ["guiso", "mexicano", "fibra", "suave"],
    rating: 4.3,
    reviewCount: 38,
    deliveryTime: "15-20 min",
  },
  {
    id: "nopales-kg",
    name: "Nopales kg",
    price: 35,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Nopales frescos sin espinas",
    inStock: true,
    stock: 15,
    brand: "Verduras Frescas",
    tags: ["mexicano", "saludable", "antioxidantes", "tradicional"],
    rating: 4.7,
    reviewCount: 73,
    deliveryTime: "15-20 min",
  },
  {
    id: "brocoli-kg",
    name: "Brócoli kg",
    price: 45,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Brócoli fresco rico en vitaminas",
    inStock: true,
    stock: 18,
    brand: "Verduras Frescas",
    tags: ["vitaminas", "antioxidantes", "saludable", "verde"],
    rating: 4.4,
    reviewCount: 62,
    deliveryTime: "15-20 min",
  },
  {
    id: "coliflor-kg",
    name: "Coliflor kg",
    price: 38,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Coliflor blanca fresca y compacta",
    inStock: true,
    stock: 12,
    brand: "Verduras Frescas",
    tags: ["blanca", "vitaminas", "versátil", "saludable"],
    rating: 4.1,
    reviewCount: 34,
    deliveryTime: "15-20 min",
  },
  {
    id: "elote-pieza",
    name: "Elote pieza",
    price: 12,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Elotes frescos amarillos dulces",
    inStock: true,
    stock: 40,
    brand: "Verduras Frescas",
    tags: ["dulce", "mexicano", "fresco", "granos"],
    rating: 4.8,
    reviewCount: 156,
    deliveryTime: "15-20 min",
  },
  {
    id: "chile-poblano-kg",
    name: "Chile Poblano kg",
    price: 42,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Chiles poblanos frescos para rellenos",
    inStock: true,
    stock: 22,
    brand: "Verduras Frescas",
    tags: ["mexicano", "rellenos", "picante suave", "tradicional"],
    rating: 4.6,
    reviewCount: 89,
    deliveryTime: "15-20 min",
  },
  {
    id: "chile-jalapeño-kg",
    name: "Chile Jalapeño kg",
    price: 38,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Chiles jalapeños frescos y picantes",
    inStock: true,
    stock: 18,
    brand: "Verduras Frescas",
    tags: ["picante", "mexicano", "condimento", "fresco"],
    rating: 4.5,
    reviewCount: 67,
    deliveryTime: "15-20 min",
  },
  {
    id: "apio-manojo",
    name: "Apio manojo",
    price: 22,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Apio fresco crujiente en manojo",
    inStock: true,
    stock: 15,
    brand: "Verduras Frescas",
    tags: ["crujiente", "ensalada", "bajo calóricas", "fibra"],
    rating: 4.2,
    reviewCount: 43,
    deliveryTime: "15-20 min",
  },
  {
    id: "betabel-kg",
    name: "Betabel kg",
    price: 35,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Betabel rojo fresco con hojas",
    inStock: true,
    stock: 14,
    brand: "Verduras Frescas",
    tags: ["antioxidantes", "dulce", "rojo", "vitaminas"],
    rating: 4.3,
    reviewCount: 29,
    deliveryTime: "15-20 min",
  },
  {
    id: "espinaca-manojo",
    name: "Espinaca manojo",
    price: 18,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Espinacas frescas ricas en hierro",
    inStock: true,
    stock: 20,
    brand: "Verduras Frescas",
    tags: ["hierro", "vitaminas", "hojas verdes", "saludable"],
    rating: 4.4,
    reviewCount: 51,
    deliveryTime: "15-20 min",
  },
  {
    id: "acelga-manojo",
    name: "Acelga manojo",
    price: 16,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Acelgas frescas con tallos blancos",
    inStock: true,
    stock: 18,
    brand: "Verduras Frescas",
    tags: ["hojas verdes", "tallos", "vitaminas", "fibra"],
    rating: 4.1,
    reviewCount: 32,
    deliveryTime: "15-20 min",
  },
  {
    id: "rabano-manojo",
    name: "Rábano manojo",
    price: 14,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Rábanos rojos frescos y picantes",
    inStock: true,
    stock: 12,
    brand: "Verduras Frescas",
    tags: ["picante", "crujiente", "ensalada", "vitamina C"],
    rating: 4.0,
    reviewCount: 25,
    deliveryTime: "15-20 min",
  },
  {
    id: "ejote-kg",
    name: "Ejotes kg",
    price: 48,
    category: "frutas-verduras",
    subcategory: "verduras",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Ejotes verdes frescos y tiernos",
    inStock: true,
    stock: 16,
    brand: "Verduras Frescas",
    tags: ["tiernos", "verdes", "fibra", "vitaminas"],
    rating: 4.3,
    reviewCount: 41,
    deliveryTime: "15-20 min",
  },

  // Hierbas aromáticas (12 productos)
  {
    id: "cilantro-manojo",
    name: "Cilantro manojo",
    price: 8,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Cilantro fresco aromático mexicano",
    inStock: true,
    stock: 30,
    brand: "Hierbas Frescas",
    tags: ["aromático", "mexicano", "condimento", "fresco"],
    rating: 4.7,
    reviewCount: 123,
    deliveryTime: "15-20 min",
  },
  {
    id: "perejil-manojo",
    name: "Perejil manojo",
    price: 8,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Perejil liso fresco y aromático",
    inStock: true,
    stock: 25,
    brand: "Hierbas Frescas",
    tags: ["aromático", "condimento", "vitamina C", "fresco"],
    rating: 4.5,
    reviewCount: 87,
    deliveryTime: "15-20 min",
  },
  {
    id: "albahaca-manojo",
    name: "Albahaca manojo",
    price: 12,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Albahaca fresca muy arom��tica",
    inStock: true,
    stock: 15,
    brand: "Hierbas Frescas",
    tags: ["aromática", "italiana", "condimento", "fresca"],
    rating: 4.6,
    reviewCount: 64,
    deliveryTime: "15-20 min",
  },
  {
    id: "hierbabuena-manojo",
    name: "Hierbabuena manojo",
    price: 10,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Hierbabuena fresca refrescante",
    inStock: true,
    stock: 20,
    brand: "Hierbas Frescas",
    tags: ["refrescante", "aromática", "té", "digestiva"],
    rating: 4.4,
    reviewCount: 52,
    deliveryTime: "15-20 min",
  },
  {
    id: "oregano-manojo",
    name: "Orégano fresco manojo",
    price: 12,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Orégano fresco muy aromático",
    inStock: true,
    stock: 12,
    brand: "Hierbas Frescas",
    tags: ["aromático", "mexicano", "pizza", "condimento"],
    rating: 4.5,
    reviewCount: 43,
    deliveryTime: "15-20 min",
  },
  {
    id: "romero-manojo",
    name: "Romero manojo",
    price: 14,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Romero fresco para carnes",
    inStock: true,
    stock: 10,
    brand: "Hierbas Frescas",
    tags: ["aromático", "carnes", "condimento", "mediterráneo"],
    rating: 4.3,
    reviewCount: 31,
    deliveryTime: "15-20 min",
  },
  {
    id: "tomillo-manojo",
    name: "Tomillo manojo",
    price: 14,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Tomillo fresco aromático",
    inStock: true,
    stock: 8,
    brand: "Hierbas Frescas",
    tags: ["aromático", "condimento", "medicinal", "fresco"],
    rating: 4.2,
    reviewCount: 26,
    deliveryTime: "15-20 min",
  },
  {
    id: "epazote-manojo",
    name: "Epazote manojo",
    price: 10,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Epazote mexicano para frijoles",
    inStock: true,
    stock: 15,
    brand: "Hierbas Frescas",
    tags: ["mexicano", "frijoles", "tradicional", "digestivo"],
    rating: 4.6,
    reviewCount: 78,
    deliveryTime: "15-20 min",
  },
  {
    id: "hoja-santa-manojo",
    name: "Hoja Santa manojo",
    price: 16,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Hoja santa mexicana aromática",
    inStock: true,
    stock: 8,
    brand: "Hierbas Frescas",
    tags: ["mexicana", "aromática", "tamales", "tradicional"],
    rating: 4.4,
    reviewCount: 35,
    deliveryTime: "15-20 min",
  },
  {
    id: "laurel-manojo",
    name: "Hojas de Laurel manojo",
    price: 12,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Hojas de laurel frescas aromáticas",
    inStock: true,
    stock: 12,
    brand: "Hierbas Frescas",
    tags: ["aromático", "guisos", "condimento", "tradicional"],
    rating: 4.3,
    reviewCount: 42,
    deliveryTime: "15-20 min",
  },
  {
    id: "eneldo-manojo",
    name: "Eneldo manojo",
    price: 16,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Eneldo fresco para pescados",
    inStock: true,
    stock: 6,
    brand: "Hierbas Frescas",
    tags: ["aromático", "pescado", "fresco", "delicado"],
    rating: 4.1,
    reviewCount: 18,
    deliveryTime: "15-20 min",
  },
  {
    id: "estragón-manojo",
    name: "Estragón manojo",
    price: 18,
    category: "frutas-verduras",
    subcategory: "hierbas-aromaticas",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Estragón fresco aromático",
    inStock: true,
    stock: 5,
    brand: "Hierbas Frescas",
    tags: ["aromático", "francés", "pollo", "salsas"],
    rating: 4.0,
    reviewCount: 12,
    deliveryTime: "15-20 min",
  },

  // Productos orgánicos (15 productos)
  {
    id: "lechuga-organica",
    name: "Lechuga Orgánica pieza",
    price: 28,
    originalPrice: 35,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1556801712-102246837aa7?auto=format&fit=crop&w=400&q=80",
    description: "Lechuga 100% orgánica certificada",
    inStock: true,
    stock: 15,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "certificado", "sin pesticidas", "saludable"],
    rating: 4.8,
    reviewCount: 92,
    deliveryTime: "15-20 min",
    organic: true,
    isOffer: true,
  },
  {
    id: "tomate-organico",
    name: "Tomate Orgánico kg",
    price: 55,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1592841200221-21e1c7d95b6b?auto=format&fit=crop&w=400&q=80",
    description: "Tomates orgánicos sin químicos",
    inStock: true,
    stock: 20,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "sin químicos", "saludable", "natural"],
    rating: 4.7,
    reviewCount: 76,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "zanahoria-organica",
    name: "Zanahoria Orgánica kg",
    price: 42,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=400&q=80",
    description: "Zanahorias orgánicas extra dulces",
    inStock: true,
    stock: 18,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "dulce", "vitamina A", "natural"],
    rating: 4.6,
    reviewCount: 65,
    deliveryTime: "15-20 min",
    organic: true,
  },
  // Continuaré con 12 productos orgánicos más...
  {
    id: "espinaca-organica",
    name: "Espinaca Orgánica manojo",
    price: 32,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Espinacas baby orgánicas tiernas",
    inStock: true,
    stock: 12,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "baby", "hierro", "tiernas"],
    rating: 4.7,
    reviewCount: 54,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "brocoli-organico",
    name: "Brócoli Orgánico kg",
    price: 68,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Brócoli orgánico rico en antioxidantes",
    inStock: true,
    stock: 10,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "antioxidantes", "superfood", "verde"],
    rating: 4.5,
    reviewCount: 41,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "manzana-organica",
    name: "Manzana Orgánica kg",
    price: 78,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=400&q=80",
    description: "Manzanas rojas orgánicas crujientes",
    inStock: true,
    stock: 22,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "crujiente", "sin cera", "natural"],
    rating: 4.8,
    reviewCount: 89,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "platano-organico",
    name: "Plátano Orgánico kg",
    price: 48,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Plátanos orgánicos extra dulces",
    inStock: true,
    stock: 16,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "dulce", "potasio", "energía"],
    rating: 4.6,
    reviewCount: 72,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "pepino-organico",
    name: "Pepino Orgánico kg",
    price: 45,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1604977042946-1eecc30f269e?auto=format&fit=crop&w=400&q=80",
    description: "Pepinos orgánicos sin químicos",
    inStock: true,
    stock: 14,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "hidratante", "natural", "crujiente"],
    rating: 4.4,
    reviewCount: 38,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "apio-organico",
    name: "Apio Orgánico manojo",
    price: 38,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Apio orgánico extra crujiente",
    inStock: true,
    stock: 8,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "crujiente", "bajo calórico", "fibra"],
    rating: 4.3,
    reviewCount: 27,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "cilantro-organico",
    name: "Cilantro Orgánico manojo",
    price: 18,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Cilantro orgánico muy aromático",
    inStock: true,
    stock: 15,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "aromático", "condimento", "natural"],
    rating: 4.7,
    reviewCount: 83,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "cebolla-organica",
    name: "Cebolla Orgánica kg",
    price: 52,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=400&q=80",
    description: "Cebollas orgánicas sin químicos",
    inStock: true,
    stock: 25,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "sin químicos", "aromático", "cocina"],
    rating: 4.5,
    reviewCount: 61,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "papa-organica",
    name: "Papa Org��nica kg",
    price: 48,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=400&q=80",
    description: "Papas orgánicas sin pesticidas",
    inStock: true,
    stock: 30,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "sin pesticidas", "natural", "versátil"],
    rating: 4.6,
    reviewCount: 94,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "limon-organico",
    name: "Limón Orgánico kg",
    price: 42,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Limones orgánicos extra jugosos",
    inStock: true,
    stock: 18,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "jugoso", "vitamina C", "natural"],
    rating: 4.7,
    reviewCount: 76,
    deliveryTime: "15-20 min",
    organic: true,
  },
  {
    id: "aguacate-organico",
    name: "Aguacate Orgánico kg",
    price: 95,
    category: "frutas-verduras",
    subcategory: "productos-organicos",
    aisle: "Pasillo 1",
    image:
      "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80",
    description: "Aguacates orgánicos cremosos",
    inStock: true,
    stock: 12,
    brand: "Orgánicos Natural",
    tags: ["orgánico", "cremoso", "grasas buenas", "premium"],
    rating: 4.9,
    reviewCount: 127,
    deliveryTime: "15-20 min",
    organic: true,
  },

  // Jugos naturales refrigerados (8 productos)
  {
    id: "jugo-naranja-natural",
    name: "Jugo de Naranja Natural 1L",
    price: 45,
    category: "frutas-verduras",
    subcategory: "jugos-naturales",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Jugo de naranja 100% natural recién exprimido",
    inStock: true,
    stock: 24,
    brand: "Jugos Naturales",
    tags: ["natural", "vitamina C", "recién exprimido", "sin azúcar"],
    rating: 4.8,
    reviewCount: 156,
    deliveryTime: "15-20 min",
  },
  {
    id: "jugo-verde-detox",
    name: "Jugo Verde Detox 500ml",
    price: 52,
    category: "frutas-verduras",
    subcategory: "jugos-naturales",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Jugo verde con espinaca, apio, pepino y manzana",
    inStock: true,
    stock: 18,
    brand: "Jugos Naturales",
    tags: ["detox", "verde", "saludable", "antioxidantes"],
    rating: 4.6,
    reviewCount: 89,
    deliveryTime: "15-20 min",
  },
  {
    id: "jugo-zanahoria",
    name: "Jugo de Zanahoria 500ml",
    price: 38,
    category: "frutas-verduras",
    subcategory: "jugos-naturales",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Jugo de zanahoria natural rico en vitamina A",
    inStock: true,
    stock: 20,
    brand: "Jugos Naturales",
    tags: ["vitamina A", "natural", "dulce", "saludable"],
    rating: 4.5,
    reviewCount: 67,
    deliveryTime: "15-20 min",
  },
  {
    id: "jugo-betabel",
    name: "Jugo de Betabel 500ml",
    price: 42,
    category: "frutas-verduras",
    subcategory: "jugos-naturales",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Jugo de betabel natural energizante",
    inStock: true,
    stock: 15,
    brand: "Jugos Naturales",
    tags: ["energizante", "antioxidantes", "natural", "deportivo"],
    rating: 4.4,
    reviewCount: 52,
    deliveryTime: "15-20 min",
  },
  {
    id: "jugo-apio",
    name: "Jugo de Apio 500ml",
    price: 35,
    category: "frutas-verduras",
    subcategory: "jugos-naturales",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Jugo de apio puro depurativo",
    inStock: true,
    stock: 12,
    brand: "Jugos Naturales",
    tags: ["depurativo", "bajo calórico", "natural", "fibra"],
    rating: 4.2,
    reviewCount: 34,
    deliveryTime: "15-20 min",
  },
  {
    id: "jugo-mixto-citricos",
    name: "Jugo Mixto de Cítricos 1L",
    price: 48,
    category: "frutas-verduras",
    subcategory: "jugos-naturales",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Mezcla de jugo de naranja, toronja y limón",
    inStock: true,
    stock: 16,
    brand: "Jugos Naturales",
    tags: ["cítrico", "vitamina C", "refrescante", "natural"],
    rating: 4.7,
    reviewCount: 78,
    deliveryTime: "15-20 min",
  },
  {
    id: "jugo-manzana-natural",
    name: "Jugo de Manzana Natural 1L",
    price: 42,
    category: "frutas-verduras",
    subcategory: "jugos-naturales",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Jugo de manzana 100% natural sin azúcar añadida",
    inStock: true,
    stock: 22,
    brand: "Jugos Naturales",
    tags: ["natural", "sin azúcar", "antioxidantes", "dulce"],
    rating: 4.6,
    reviewCount: 95,
    deliveryTime: "15-20 min",
  },
  {
    id: "agua-fresca-jamaica",
    name: "Agua Fresca de Jamaica 1L",
    price: 32,
    category: "frutas-verduras",
    subcategory: "jugos-naturales",
    aisle: "Pasillo 1",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Agua fresca de jamaica natural sin azúcar",
    inStock: true,
    stock: 18,
    brand: "Jugos Naturales",
    tags: ["jamaica", "natural", "antioxidantes", "refrescante"],
    rating: 4.5,
    reviewCount: 63,
    deliveryTime: "15-20 min",
  },

  // PASILLO 2 - PANADERÍA Y TORTILLERÍA (45 productos)
  // Pan dulce y salado (15 productos)
  {
    id: "pan-blanco-bimbo-grande",
    name: "Pan Blanco Bimbo Grande",
    price: 38,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Pan dulce tradicional mexicano",
    inStock: true,
    stock: 12,
    brand: "Panadería Local",
    tags: ["tradicional", "mexicano", "dulce", "hojaldre"],
    rating: 4.4,
    reviewCount: 58,
    deliveryTime: "15-20 min",
  },
  {
    id: "elote-pan",
    name: "Pan de Elote",
    price: 20,
    category: "panaderia-bimbo",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Pan dulce sabor elote muy mexicano",
    inStock: true,
    stock: 10,
    brand: "Panadería Local",
    tags: ["elote", "mexicano", "sabor", "dulce"],
    rating: 4.6,
    reviewCount: 72,
    deliveryTime: "15-20 min",
  },
  {
    id: "polvoron",
    name: "Polvorón",
    price: 14,
    category: "panaderia-bimbo",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Concha mexicana con cobertura de chocolate",
    inStock: true,
    stock: 24,
    brand: "Panadería Local",
    tags: ["concha", "chocolate", "dulce", "mexicano"],
    rating: 4.8,
    reviewCount: 156,
    deliveryTime: "15-20 min",
  },
  {
    id: "concha-vainilla",
    name: "Concha de Vainilla",
    price: 12,
    category: "panaderia-bimbo",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Concha mexicana tradicional de vainilla",
    inStock: true,
    stock: 24,
    brand: "Panadería Local",
    tags: ["concha", "vainilla", "dulce", "tradicional"],
    rating: 4.7,
    reviewCount: 142,
    deliveryTime: "15-20 min",
  },
  {
    id: "cuerno-mantequilla",
    name: "Cuerno de Mantequilla",
    price: 14,
    category: "panaderia-bimbo",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Cuerno dulce esponjoso con mantequilla",
    inStock: true,
    stock: 18,
    brand: "Panadería Local",
    tags: ["cuerno", "mantequilla", "esponjoso", "dulce"],
    rating: 4.6,
    reviewCount: 87,
    deliveryTime: "15-20 min",
  },
  {
    id: "dona-azucar",
    name: "Dona Azucarada",
    price: 15,
    category: "panaderia-bimbo",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Dona esponjosa cubierta de azúcar",
    inStock: true,
    stock: 20,
    brand: "Panadería Local",
    tags: ["dona", "azúcar", "esponjosa", "dulce"],
    rating: 4.5,
    reviewCount: 76,
    deliveryTime: "15-20 min",
  },
  {
    id: "dona-chocolate",
    name: "Dona de Chocolate",
    price: 18,
    category: "panaderia-bimbo",
    inStock: true,
    stock: 50,
    brand: "Panadería Local",
    tags: ["bolillo", "crujiente", "tradicional", "mexicano"],
    rating: 4.7,
    reviewCount: 134,
    deliveryTime: "15-20 min",
  },
  {
    id: "concha-chocolate",
    name: "Concha de Chocolate",
    price: 12,
    category: "panaderia-bimbo",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Dona con glaseado de chocolate",
    inStock: true,
    stock: 16,
    brand: "Panadería Local",
    tags: ["dona", "chocolate", "glaseado", "premium"],
    rating: 4.7,
    reviewCount: 94,
    deliveryTime: "15-20 min",
  },
  {
    id: "ojo-buey",
    name: "Ojo de Buey",
    price: 16,
    category: "panaderia-tortilleria",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Pan dulce tradicional mexicano",
    inStock: true,
    stock: 12,
    brand: "Panadería Local",
    tags: ["tradicional", "mexicano", "dulce", "hojaldre"],
    rating: 4.4,
    reviewCount: 58,
    deliveryTime: "15-20 min",
  },
  {
    id: "elote-pan",
    name: "Pan de Elote",
    price: 20,
    category: "panaderia-tortilleria",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Pan dulce sabor elote muy mexicano",
    inStock: true,
    stock: 10,
    brand: "Panadería Local",
    tags: ["elote", "mexicano", "sabor", "dulce"],
    rating: 4.6,
    reviewCount: 72,
    deliveryTime: "15-20 min",
  },
  {
    id: "polvoron",
    name: "Polvorón",
    price: 14,
    category: "panaderia-tortilleria",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Polvorón tradicional que se deshace en la boca",
    inStock: true,
    stock: 14,
    brand: "Panadería Local",
    tags: ["polvorón", "tradicional", "deshace", "dulce"],
    rating: 4.5,
    reviewCount: 63,
    deliveryTime: "15-20 min",
  },
  {
    id: "empanada-dulce",
    name: "Empanada de Dulce",
    price: 16,
    category: "panaderia-tortilleria",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Empanada rellena de dulce de leche",
    inStock: true,
    stock: 12,
    brand: "Panadería Local",
    tags: ["empanada", "dulce de leche", "rellena", "tradicional"],
    rating: 4.6,
    reviewCount: 81,
    deliveryTime: "15-20 min",
  },
  {
    id: "gusano-dulce",
    name: "Gusano de Pan Dulce",
    price: 18,
    category: "panaderia-tortilleria",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    description: "Pan dulce en forma de gusano con azúcar",
    inStock: true,
    stock: 8,
    brand: "Panadería Local",
    tags: ["gusano", "azúcar", "forma", "divertido"],
    rating: 4.3,
    reviewCount: 47,
    deliveryTime: "15-20 min",
  },
  {
    id: "baguette-frances",
    name: "Baguette Francés",
    price: 25,
    category: "panaderia-tortilleria",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Imagen+del+Producto",
    inStock: true,
    stock: 8,
    brand: "Panadería Local",
    tags: ["baguette", "francés", "crujiente", "artesanal"],
    rating: 4.7,
    reviewCount: 92,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-tostado",
    name: "Pan Tostado Integral",
    price: 35,
    category: "panaderia-tortilleria",
    subcategory: "pan-dulce-salado",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
    description: "Pan tostado integral en rebanadas",
    inStock: true,
    stock: 12,
    brand: "Bimbo",
    tags: ["tostado", "integral", "rebanadas", "crocante"],
    rating: 4.4,
    reviewCount: 56,
    deliveryTime: "15-20 min",
  },

  // Pasteles y postres (10 productos)
  {
    id: "pastel-tres-leches",
    name: "Pastel Tres Leches Individual",
    price: 45,
    category: "panaderia-tortilleria",
    subcategory: "pasteles-postres",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Delicioso pastel tres leches individual",
    inStock: true,
    stock: 12,
    brand: "Repostería Dulce",
    tags: ["tres leches", "individual", "cremoso", "tradicional"],
    rating: 4.9,
    reviewCount: 145,
    deliveryTime: "15-20 min",
  },
  {
    id: "flan-napolitano",
    name: "Flan Napolitano Individual",
    price: 28,
    category: "panaderia-tortilleria",
    subcategory: "pasteles-postres",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Flan napolitano cremoso con caramelo",
    inStock: true,
    stock: 18,
    brand: "Repostería Dulce",
    tags: ["flan", "napolitano", "caramelo", "cremoso"],
    rating: 4.7,
    reviewCount: 98,
    deliveryTime: "15-20 min",
  },
  {
    id: "gelatina-mosaico",
    name: "Gelatina Mosaico",
    price: 22,
    category: "panaderia-tortilleria",
    subcategory: "pasteles-postres",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Gelatina de colores mosaico refrescante",
    inStock: true,
    stock: 15,
    brand: "Repostería Dulce",
    tags: ["gelatina", "mosaico", "colores", "refrescante"],
    rating: 4.5,
    reviewCount: 73,
    deliveryTime: "15-20 min",
  },
  {
    id: "carlota-limon",
    name: "Carlota de Limón",
    price: 35,
    category: "panaderia-tortilleria",
    subcategory: "pasteles-postres",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Carlota de limón con galletas marías",
    inStock: true,
    stock: 10,
    brand: "Repostería Dulce",
    tags: ["carlota", "limón", "galletas", "cremosa"],
    rating: 4.6,
    reviewCount: 84,
    deliveryTime: "15-20 min",
  },
  {
    id: "mousse-chocolate",
    name: "Mousse de Chocolate",
    price: 42,
    category: "panaderia-tortilleria",
    subcategory: "pasteles-postres",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Mousse de chocolate intenso y cremoso",
    inStock: true,
    stock: 8,
    brand: "Repostería Dulce",
    tags: ["mousse", "chocolate", "intenso", "cremoso"],
    rating: 4.8,
    reviewCount: 67,
    deliveryTime: "15-20 min",
  },
  {
    id: "tiramisu-individual",
    name: "Tiramisú Individual",
    price: 55,
    category: "panaderia-tortilleria",
    subcategory: "pasteles-postres",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Tiramisú italiano auténtico individual",
    inStock: true,
    stock: 6,
    brand: "Repostería Dulce",
    tags: ["tiramisú", "italiano", "café", "premium"],
    rating: 4.9,
    reviewCount: 52,
    deliveryTime: "15-20 min",
  },
  {
    id: "cheesecake-fresa",
    name: "Cheesecake de Fresa",
    price: 48,
    category: "panaderia-tortilleria",
    subcategory: "pasteles-postres",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Cheesecake cremoso con mermelada de fresa",
    inStock: true,
    stock: 7,
    brand: "Repostería Dulce",
    tags: ["cheesecake", "fresa", "cremoso", "mermelada"],
    rating: 4.7,
    reviewCount: 89,
    deliveryTime: "15-20 min",
  },
  {
    id: "pastel-chocolate",
    name: "Pastel de Chocolate Individual",
    price: 38,
    category: "panaderia-tortilleria",
    subcategory: "pasteles-postres",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Pastel de chocolate húmedo individual",
    inStock: true,
    stock: 14,
    brand: "Repostería Dulce",
    tags: ["chocolate", "húmedo", "individual", "clásico"],
    rating: 4.6,
    reviewCount: 76,
    deliveryTime: "15-20 min",
  },
  {
    id: "brownie-nuez",
    name: "Brownie con Nuez",
    price: 32,
    category: "panaderia-tortilleria",
    subcategory: "pasteles-postres",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Brownie de chocolate con trozos de nuez",
    inStock: true,
    stock: 16,
    brand: "Repostería Dulce",
    tags: ["brownie", "chocolate", "nuez", "trozos"],
    rating: 4.5,
    reviewCount: 93,
    deliveryTime: "15-20 min",
  },
  {
    id: "pay-queso",
    name: "Pay de Queso",
    price: 45,
    category: "panaderia-tortilleria",
    subcategory: "pasteles-postres",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Pay de queso tradicional mexicano",
    inStock: true,
    stock: 9,
    brand: "Repostería Dulce",
    tags: ["pay", "queso", "tradicional", "mexicano"],
    rating: 4.7,
    reviewCount: 101,
    deliveryTime: "15-20 min",
  },

  // Tortillas de maíz y harina (8 productos)
  {
    id: "tortillas-maiz-kg",
    name: "Tortillas de Maíz kg",
    price: 18,
    category: "panaderia-tortilleria",
    subcategory: "tortillas",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=400&q=80",
    description: "Tortillas de maíz frescas hechas diariamente",
    inStock: true,
    stock: 40,
    brand: "Tortillería Local",
    tags: ["tortilla", "maíz", "fresco", "tradicional"],
    rating: 4.8,
    reviewCount: 156,
    deliveryTime: "15-20 min",
  },
  {
    id: "tortillas-harina-kg",
    name: "Tortillas de Harina kg",
    price: 24,
    category: "panaderia-tortilleria",
    subcategory: "tortillas",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=400&q=80",
    description: "Tortillas de harina suaves y flexibles",
    inStock: true,
    stock: 35,
    brand: "Tortillería Local",
    tags: ["tortilla", "harina", "suave", "flexible"],
    rating: 4.7,
    reviewCount: 134,
    deliveryTime: "15-20 min",
  },
  {
    id: "tortillas-integrales",
    name: "Tortillas Integrales kg",
    price: 32,
    category: "panaderia-tortilleria",
    subcategory: "tortillas",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=400&q=80",
    description: "Tortillas de harina integral con fibra",
    inStock: true,
    stock: 20,
    brand: "Tortillería Local",
    tags: ["integral", "fibra", "saludable", "harina"],
    rating: 4.5,
    reviewCount: 78,
    deliveryTime: "15-20 min",
  },
  {
    id: "tortillas-tostadas",
    name: "Tostadas de Maíz paquete",
    price: 16,
    category: "panaderia-tortilleria",
    subcategory: "tortillas",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=400&q=80",
    description: "Tostadas de maíz crujientes para garnachas",
    inStock: true,
    stock: 30,
    brand: "Tortillería Local",
    tags: ["tostadas", "crujientes", "garnachas", "maíz"],
    rating: 4.6,
    reviewCount: 89,
    deliveryTime: "15-20 min",
  },
  {
    id: "tortillas-nopal",
    name: "Tortillas de Nopal kg",
    price: 38,
    category: "panaderia-tortilleria",
    subcategory: "tortillas",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=400&q=80",
    description: "Tortillas de nopal nutritivas y saludables",
    inStock: true,
    stock: 15,
    brand: "Tortillería Local",
    tags: ["nopal", "nutritivas", "saludables", "mexicanas"],
    rating: 4.4,
    reviewCount: 52,
    deliveryTime: "15-20 min",
  },
  {
    id: "tortillas-azules",
    name: "Tortillas de Maíz Azul kg",
    price: 28,
    category: "panaderia-tortilleria",
    subcategory: "tortillas",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=400&q=80",
    description: "Tortillas de maíz azul tradicionales",
    inStock: true,
    stock: 18,
    brand: "Tortillería Local",
    tags: ["maíz azul", "tradicionales", "antioxidantes", "especiales"],
    rating: 4.7,
    reviewCount: 67,
    deliveryTime: "15-20 min",
  },
  {
    id: "sopes-maiz",
    name: "Sopes de Maíz 6 piezas",
    price: 22,
    category: "panaderia-tortilleria",
    subcategory: "tortillas",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=400&q=80",
    description: "Sopes de maíz frescos listos para rellenar",
    inStock: true,
    stock: 25,
    brand: "Tortiller��a Local",
    tags: ["sopes", "maíz", "frescos", "mexicanos"],
    rating: 4.8,
    reviewCount: 94,
    deliveryTime: "15-20 min",
  },
  {
    id: "huaraches-masa",
    name: "Huaraches de Masa 4 piezas",
    price: 28,
    category: "panaderia-tortilleria",
    subcategory: "tortillas",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?auto=format&fit=crop&w=400&q=80",
    description: "Huaraches de masa fresca tradicionales",
    inStock: true,
    stock: 12,
    brand: "Tortillería Local",
    tags: ["huaraches", "masa", "tradicionales", "mexicanos"],
    rating: 4.6,
    reviewCount: 73,
    deliveryTime: "15-20 min",
  },

  // Bolillos y baguettes (6 productos)
  {
    id: "bolillo-tradicional",
    name: "Bolillo Tradicional 6 piezas",
    price: 20,
    category: "panaderia-tortilleria",
    subcategory: "bolillos-baguettes",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
    description: "Bolillos tradicionales mexicanos crujientes",
    inStock: true,
    stock: 30,
    brand: "Panadería Local",
    tags: ["bolillo", "tradicional", "crujiente", "mexicano"],
    rating: 4.7,
    reviewCount: 112,
    deliveryTime: "15-20 min",
  },
  {
    id: "baguette-artesanal",
    name: "Baguette Artesanal",
    price: 35,
    category: "panaderia-tortilleria",
    subcategory: "bolillos-baguettes",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
    description: "Baguette francés artesanal recién horneado",
    inStock: true,
    stock: 12,
    brand: "Panadería Local",
    tags: ["baguette", "artesanal", "francés", "horneado"],
    rating: 4.8,
    reviewCount: 89,
    deliveryTime: "15-20 min",
  },
  {
    id: "chapata-italiana",
    name: "Chapata Italiana",
    price: 28,
    category: "panaderia-tortilleria",
    subcategory: "bolillos-baguettes",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
    description: "Pan chapata italiano con aceitunas",
    inStock: true,
    stock: 8,
    brand: "Panadería Local",
    tags: ["chapata", "italiana", "aceitunas", "artesanal"],
    rating: 4.6,
    reviewCount: 54,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-centeno",
    name: "Pan de Centeno",
    price: 42,
    category: "panaderia-tortilleria",
    subcategory: "bolillos-baguettes",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
    description: "Pan de centeno denso y nutritivo",
    inStock: true,
    stock: 6,
    brand: "Panadería Local",
    tags: ["centeno", "denso", "nutritivo", "fibra"],
    rating: 4.4,
    reviewCount: 38,
    deliveryTime: "15-20 min",
  },
  {
    id: "pan-multigrano",
    name: "Pan Multigrano",
    price: 38,
    category: "panaderia-tortilleria",
    subcategory: "bolillos-baguettes",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
    description: "Pan con mezcla de granos y semillas",
    inStock: true,
    stock: 10,
    brand: "Panadería Local",
    tags: ["multigrano", "granos", "semillas", "saludable"],
    rating: 4.5,
    reviewCount: 67,
    deliveryTime: "15-20 min",
  },
  {
    id: "focaccia-hierbas",
    name: "Focaccia con Hierbas",
    price: 45,
    category: "panaderia-tortilleria",
    subcategory: "bolillos-baguettes",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
    description: "Focaccia italiana con hierbas aromáticas",
    inStock: true,
    stock: 5,
    brand: "Panadería Local",
    tags: ["focaccia", "italiana", "hierbas", "aromáticas"],
    rating: 4.7,
    reviewCount: 43,
    deliveryTime: "15-20 min",
  },

  // Galletas y biscochos (12 productos)
  {
    id: "galletas-marias",
    name: "Galletas Marías Gamesa",
    price: 16,
    category: "panaderia-bimbo",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Galletas Marías clásicas de Gamesa",
    inStock: true,
    stock: 25,
    brand: "Gamesa",
    tags: ["marías", "clásicas", "tradicionales", "té"],
    rating: 4.6,
    reviewCount: 89,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-emperador",
    name: "Galletas Emperador",
    price: 24,
    category: "panaderia-tortilleria",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Galletas Emperador rellenas de chocolate",
    inStock: true,
    stock: 20,
    brand: "Gamesa",
    tags: ["emperador", "chocolate", "rellenas", "crema"],
    rating: 4.7,
    reviewCount: 134,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-chokis",
    name: "Galletas Chokis",
    price: 18,
    category: "panaderia-tortilleria",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Galletas con chispas de chocolate",
    inStock: true,
    stock: 22,
    brand: "Gamesa",
    tags: ["chokis", "chispas", "chocolate", "dulces"],
    rating: 4.8,
    reviewCount: 156,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-animalitos",
    name: "Galletas Animalitos",
    price: 14,
    category: "panaderia-tortilleria",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Galletas en forma de animalitos para niños",
    inStock: true,
    stock: 28,
    brand: "Gamesa",
    tags: ["animalitos", "niños", "formas", "divertidas"],
    rating: 4.5,
    reviewCount: 92,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-arcoiris",
    name: "Galletas Arcoíris",
    price: 20,
    category: "panaderia-tortilleria",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Galletas de colores tipo arcoíris",
    inStock: true,
    stock: 18,
    brand: "Gamesa",
    tags: ["arcoíris", "colores", "vainilla", "crema"],
    rating: 4.4,
    reviewCount: 76,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-saladitas",
    name: "Galletas Saladitas",
    price: 22,
    category: "panaderia-tortilleria",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Galletas saladas tipo crackers",
    inStock: true,
    stock: 16,
    brand: "Gamesa",
    tags: ["saladas", "crackers", "aperitivo", "crujientes"],
    rating: 4.3,
    reviewCount: 58,
    deliveryTime: "15-20 min",
  },
  {
    id: "polvorones-mexicanos",
    name: "Polvorones Mexicanos",
    price: 26,
    category: "panaderia-tortilleria",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Polvorones tradicionales mexicanos",
    inStock: true,
    stock: 12,
    brand: "Dulces Tradicionales",
    tags: ["polvorones", "mexicanos", "tradicionales", "canela"],
    rating: 4.6,
    reviewCount: 84,
    deliveryTime: "15-20 min",
  },
  {
    id: "biscochos-canela",
    name: "Biscochos de Canela",
    price: 28,
    category: "panaderia-tortilleria",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Biscochos dulces con canela",
    inStock: true,
    stock: 14,
    brand: "Dulces Tradicionales",
    tags: ["biscochos", "canela", "dulces", "aromáticos"],
    rating: 4.5,
    reviewCount: 67,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-avena",
    name: "Galletas de Avena",
    price: 32,
    category: "panaderia-tortilleria",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Galletas de avena con pasas",
    inStock: true,
    stock: 10,
    brand: "Dulces Tradicionales",
    tags: ["avena", "pasas", "saludables", "fibra"],
    rating: 4.4,
    reviewCount: 52,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-coco",
    name: "Galletas de Coco",
    price: 24,
    category: "panaderia-tortilleria",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Galletas dulces con coco rallado",
    inStock: true,
    stock: 15,
    brand: "Dulces Tradicionales",
    tags: ["coco", "rallado", "dulces", "tropical"],
    rating: 4.6,
    reviewCount: 73,
    deliveryTime: "15-20 min",
  },
  {
    id: "amarantos-dulces",
    name: "Amarantos Dulces",
    price: 18,
    category: "panaderia-tortilleria",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Amarantos mexicanos con miel",
    inStock: true,
    stock: 20,
    brand: "Dulces Tradicionales",
    tags: ["amaranto", "miel", "mexicanos", "nutritivos"],
    rating: 4.7,
    reviewCount: 98,
    deliveryTime: "15-20 min",
  },
  {
    id: "galletas-mantequilla",
    name: "Galletas de Mantequilla",
    price: 26,
    category: "panaderia-tortilleria",
    subcategory: "galletas-biscochos",
    aisle: "Pasillo 2",
    image:
      "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80",
    description: "Galletas caseras sabor mantequilla",
    inStock: true,
    stock: 12,
    brand: "Dulces Tradicionales",
    tags: ["mantequilla", "caseras", "cremosas", "clásicas"],
    rating: 4.5,
    reviewCount: 61,
    deliveryTime: "15-20 min",
  },
];

export const quickCategories = [
  { name: "Ofertas", icon: "🏷️", color: "bg-red-500" },
  { name: "Nuevos", icon: "✨", color: "bg-yellow-500" },
  { name: "Más vendidos", icon: "🔥", color: "bg-brand-500" },
  { name: "Delivery rápido", icon: "⚡", color: "bg-red-400" },
  { name: "Disponible ahora", icon: "🕘", color: "bg-fresh-500" },
];

export const deliveryOptions = [
  {
    id: "express",
    name: "Express",
    time: "15-20 min",
    price: 25,
    icon: "⚡",
    description: "Lo más rápido posible",
  },
  {
    id: "standard",
    name: "Estándar",
    time: "30-45 min",
    price: 15,
    icon: "🚗",
    description: "Entrega regular",
  },
  {
    id: "pickup",
    name: "Recoger en tienda",
    time: "10-15 min",
    price: 0,
    icon: "🏪",
    description: "Sin costo de envío",
  },
];

// Función para verificar si la tienda está abierta
export const isStoreOpen = (): boolean => {
  const now = new Date();
  const currentHour = now.getHours();
  const openHour = parseInt(storeHours.open.split(":")[0]);
  const closeHour = parseInt(storeHours.close.split(":")[0]);

  return currentHour >= openHour && currentHour < closeHour;
};

// Función para obtener el próximo horario de apertura
export const getNextOpenTime = (): string => {
  const now = new Date();
  const tomorrow = new Date(now);
  tomorrow.setDate(tomorrow.getDate() + 1);

  if (now.getHours() >= parseInt(storeHours.close.split(":")[0])) {
    return `Mañana a las ${storeHours.open}`;
  } else {
    return `Hoy a las ${storeHours.open}`;
  }
};

// Importar productos adicionales
import additionalProducts from "./data-extended";
import { bimboProducts } from "./bimbo-products";
import { addTestProducts } from "./test-products";

// Filtrar productos de panadería del array principal para reemplazarlos con Bimbo
const productsWithoutPanaderia = products.filter(
  (product) => product.category !== "panaderia-bimbo",
);

// Combinar todos los productos
export const allProducts: Product[] = [
  ...productsWithoutPanaderia,
  ...bimboProducts,
  ...additionalProducts,
  ...addTestProducts(), // Agregar productos de prueba en desarrollo
];

// Función para obtener el total de productos
export const getTotalProducts = (): number => {
  return allProducts.length;
};

// Función para obtener productos por categoría
export const getProductsByCategory = (categoryId: string): Product[] => {
  return allProducts.filter((product) => product.category === categoryId);
};

// Función para obtener el conteo de productos por categoría
export const getProductCountByCategory = (categoryId: string): number => {
  return getProductsByCategory(categoryId).length;
};

// Función para obtener el conteo de productos por pasillo
export const getProductCountByAisle = (aisle: string): number => {
  return allProducts.filter((product) => product.aisle === aisle).length;
};

// Función para obtener estadísticas generales
export const getProductStats = () => {
  const totalProducts = getTotalProducts();
  const inStockProducts = allProducts.filter(
    (product) => product.inStock,
  ).length;
  const outOfStockProducts = totalProducts - inStockProducts;
  const totalCategories = categories.length;

  return {
    totalProducts,
    inStockProducts,
    outOfStockProducts,
    totalCategories,
    averagePrice:
      allProducts.reduce((sum, product) => sum + product.price, 0) /
      totalProducts,
  };
};
